In [ ]:
from google.colab import drive

# Mount Google Drive (optional)
drive.mount('/content/drive')

# Clone your GitHub repository
!git clone https://github.com/beingAnujChaudhary/personalNotes.git

# Move into repository
%cd /content/personalNotes

# Move into Chapter 1 folder
%cd notebooks/02_numpy

# 🚀 NumPy Part 3: Advanced Manipulation, Statistics & Set Operations

Welcome to Part 3! In this notebook, we transition from basic array creation to **powerful data manipulation, statistical analysis, and conditional logic**. These are the exact functions used daily in Pandas, Scikit-Learn, and Deep Learning frameworks.

## 🗺️ Roadmap
1. **Sorting & Searching** (`sort`, `unique`, `where`, `argmax`)
2. **Joining & Modifying** (`concatenate`, `append`, `delete`, `expand_dims`, `flip`)
3. **Cumulative Math & Stats** (`cumsum`, `percentile`, `histogram`, `corrcoef`)
4. **Set Operations & Clipping** (`union1d`, `intersect1d`, `clip`, `allclose`)

Let's dive in! 🏊‍♂️


In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

print("🚀 NumPy Part 3 Initialized!")
print(f"NumPy Version: {np.__version__}")


🚀 NumPy Part 3 Initialized!
NumPy Version: 2.5.0


# 📊 Concept 1: Sorting & Finding Unique Elements

## 📝 Theory
- **`np.sort()`**: Returns a *sorted copy* of an array.
- **`np.unique()`**: Finds the unique elements in an array. It can also return the indices and counts of each unique element!

## 📊 Visual Diagram
```text
Original:  [3, 1, 2, 3, 1, 4]
   ↓ np.sort()
Sorted:    [1, 1, 2, 3, 3, 4]

   ↓ np.unique(return_counts=True)
Values:    [1, 2, 3, 4]
Counts:    [2, 1, 2, 1]
```

## ⚠️ Common Mistake
Using `arr.sort()` instead of `np.sort(arr)`. 
- `np.sort(arr)` returns a **copy** (original is unchanged).
- `arr.sort()` sorts **in-place** (modifies original, returns `None`).

## 🏋️ Practice Tasks
### 🟢 Easy
1. Sort a 1D array of random integers.
2. Find the unique values in an array.

### 🟡 Medium
3. Sort a 2D array **column-wise** (along `axis=0`).
4. Use `np.unique` to find how many times each number appears in an array.

### 🔴 Hard
5. Given a 2D array, flatten it, sort it, and find the top 3 most frequent elements.
6. Do reverse sorting on arr1D and arr2D?

<details>
<summary>Click for solution</summary>

```
# ==========================================
# 💻 CONCEPT 1: SORTING & UNIQUE
# ==========================================
arr = np.array([3, 1, 2, 3, 1, 4])

# Easy
print("Sorted:", np.sort(arr))
print("Unique:", np.unique(arr))

# Medium
mat = np.array([[3, 1, 2], [1, 5, 2]])
print("\nSorted Column-wise (axis=0):\n", np.sort(mat, axis=0))

vals, counts = np.unique(arr, return_counts=True)
print(f"\nValue Counts:\n{dict(zip(vals, counts))}")

# Hard & Mini Challenge
np.random.seed(42)
rand_arr = np.random.randint(1, 11, 100)
vals, counts = np.unique(rand_arr, return_counts=True)
most_frequent = vals[np.argmax(counts)]
print(f"\nMini Challenge - Most frequent value: {most_frequent} (appeared {np.max(counts)} times)")
```

</details>

In [ ]:
# First Problem
arr1D = np.random.randint(1, 10, 20)
print(arr1D)

print("Sorted array by using np.sort(arr):\n", np.sort(arr1D), "\nOriginal array arr remained unchanged:\n", arr)

[4 8 5 4 7 5 5 5 2 1 7 3 4 4 1 2 6 5 2 8]
Sorted array by using np.sort(arr):
 [1 1 2 2 2 3 4 4 4 4 5 5 5 5 5 6 7 7 8 8] 
Original array arr remained unchanged:
 [4 2 8 7 1 5 4 8 5 7 3 6 1 1 4 8 8 3 1 8]


In [ ]:
# Second Problem
print(np.unique(arr1D))

[1 2 3 4 5 6 7 8]


In [ ]:
# Third Problem
arr2D = np.random.randint(1, 20, 12).reshape(3, 4)
print(arr2D)
print("\n Sorted arr2D column wise:\n", np.sort(arr2D, axis=0))
print("\n Sorted arr2D row wise:\n", np.sort(arr2D, axis=1))

[[11  1 13 11]
 [11 11  4 13]
 [16 13  9  1]]

 Sorted arr2D column wise:
 [[11  1  4  1]
 [11 11  9 11]
 [16 13 13 13]]

 Sorted arr2D row wise:
 [[ 1 11 11 13]
 [ 4 11 11 13]
 [ 1  9 13 16]]


In [ ]:
# Fourth Problem
vals, counts = np.unique(arr1D, return_counts=True)
print(arr1D, vals, counts, sep="\n")
vals, counts = np.unique(arr2D, return_counts=True)
print("\n\n", arr2D, vals, counts, sep="\n")


[4 8 5 4 7 5 5 5 2 1 7 3 4 4 1 2 6 5 2 8]
[1 2 3 4 5 6 7 8]
[2 3 1 4 5 1 2 2]



[[11  1 13 11]
 [11 11  4 13]
 [16 13  9  1]]
[ 1  4  9 11 13 16]
[2 1 1 4 3 1]


In [50]:
# Fifth Problem

# Sample 2D array
arr = np.array([
    [5, 1, 3],
    [1, 5, 5],
    [2, 3, 1]
])

# 1. Flatten the array
flat_arr = arr.flatten()

# 2. Sort the array
sorted_arr = np.sort(flat_arr)

# 3. Find the top 3 most frequent elements
# Get unique values and their counts
unique_vals, counts = np.unique(sorted_arr, return_counts=True)

# np.argsort returns the indices that would sort the array (in ascending order).
# We slice [-3:] to get the last 3 (the highest), and [::-1] to reverse them so the highest is first.
top_3_indices = np.argsort(counts)[-3:][::-1]

# Pair the values with their counts
top_3_frequent = list(zip(unique_vals[top_3_indices], counts[top_3_indices]))
print("Flatten Array:", flat_arr)
print("Sorted Array:", sorted_arr)
print("Unique and Counts:", unique_vals, counts, sep="\n")
print("Top 3 Most Frequent:", top_3_frequent)

Flatten Array: [5 1 3 1 5 5 2 3 1]
Sorted Array: [1 1 1 2 3 3 5 5 5]
Unique and Counts:
[1 2 3 5]
[3 1 2 3]
Top 3 Most Frequent: [(np.int64(5), np.int64(3)), (np.int64(1), np.int64(3)), (np.int64(3), np.int64(2))]


In [58]:
# Sixth Problem: Do reverse sorting on arr1D and arr2D?

print("Sorted 1D array", np.sort(arr1D), "Reverse 1D array", np.sort(arr1D)[::-1], sep="\n")
print("Sorted 2D array", np.sort(arr2D, axis=0), "Reverse 2D array", np.sort(arr2D, axis=0)[::-1], sep="\n")


Sorted 1D array
[1 1 2 2 2 3 4 4 4 4 5 5 5 5 5 6 7 7 8 8]
Reverse 1D array
[8 8 7 7 6 5 5 5 5 5 4 4 4 4 3 2 2 2 1 1]
Sorted 2D array
[[11  1  4  1]
 [11 11  9 11]
 [16 13 13 13]]
Reverse 2D array
[[16 13 13 13]
 [11 11  9 11]
 [11  1  4  1]]


## 🚀 Mini Challenge
Create an array of 100 random integers between 1 and 10. Find the unique values and their counts, then print the value that appears the most.

In [41]:
# 1. Create an array of 100 random integers between 1 and 10 (inclusive)
# Note: np.random.randint(low, high) goes up to, but does NOT include, the high value.
arr = np.random.randint(1, 11, size=100)

# 2. Find the unique values and their counts
unique_vals, counts = np.unique(arr, return_counts=True)

# 3. Find the value that appears the most
# np.argmax() finds the highest number in the 'counts' array and returns its index position.
max_index = np.argmax(counts) 

# We use that index to pull the corresponding number from the 'unique_vals' array.
most_frequent = unique_vals[max_index]

print(f"Unique values: {unique_vals}")
print(f"Counts:        {counts}")
print(f"\nThe value that appears the most is {most_frequent} (it appeared {counts[max_index]} times).")


Unique values: [ 1  2  3  4  5  6  7  8  9 10]
Counts:        [ 9 10 12  7 13  9 11  7 11 11]

The value that appears the most is 5 (it appeared 13 times).


## 🎤 Interview Question
**Q: What is the difference between `np.sort()` and `arr.sort()`?**
> **A:** `np.sort()` returns a sorted copy of the array, leaving the original unchanged. `arr.sort()` modifies the array *in-place* and returns `None`. In functional programming or data pipelines, `np.sort()` is generally preferred to avoid unintended side effects.

## 💡 Fun Fact
`np.unique()` is actually implemented using `np.sort()` under the hood! It sorts the array first, then looks for adjacent duplicates.


# 🎯 Concept 2: Conditional Logic & Searching

## 📝 Theory
- **`np.where(condition, [x, y])`**: The vectorized version of `if-else`. If `x` and `y` are provided, it returns elements from `x` where condition is True, else `y`. If only `condition` is provided, it returns the **indices** where True.
- **`np.argmax()` / `np.argmin()`**: Returns the *indices* of the maximum/minimum values.
- **`np.isin(element, test_elements)`**: Checks if each element of an array is present in a test list.

## 📊 Visual Diagram
```text
Array:      [ 1, -2,  3, -4,  5]
Condition:  [ T,  F,  T,  F,  T]  (arr > 0)

np.where(cond, arr, 0):
Result:     [ 1,  0,  3,  0,  5]  (Replaces negatives with 0 -> ReLU!)

np.where(cond):
Result:     (array([0, 2, 4]),)   (Returns indices of True)
```

## ⚠️ Common Mistake
Forgetting that `np.where(condition)` returns a **tuple** of arrays (one for each dimension). To get a flat array of indices, use `np.where(condition)[0]` or `np.nonzero(condition)[0]`.



### `np.where`

In [115]:
# Sample array for context
arr1D = np.array([2, 8, 4, 9, 5, 12])
print(arr1D)

# ---------------------------------------------------------
# Usage 1: Finding Indices (The "Where is it?" method)
# ---------------------------------------------------------
# When you only provide a condition (no replacement values), 
# np.where() returns the *index positions* where the condition is True.
# In our array [2, 8, 4, 9, 5, 12], the values > 5 are 8, 9, and 12.
# These are located at index 1, 3, and 5.
# Output: (array([1, 3, 5]),)
np.where(arr1D > 5)

[ 2  8  4  9  5 12]


(array([1, 3, 5]),)

In [116]:
# ---------------------------------------------------------
# Usage 2: Conditional Replacement (The "If This, Then That" method)
# ---------------------------------------------------------
# Syntax: np.where(condition, value_if_true, value_if_false)
# This scans every element in the array. 
# If an element is > 5, it gets replaced by 10.
# If it is NOT > 5 (meaning it's 5 or less), it stays as its original value (arr1D).
# Output: [ 2 10  4 10  5 10]
np.where(arr1D > 5, 10, arr1D)

array([ 2, 10,  4, 10,  5, 10])

In [ ]:
# Capping extreme values (Outlier Control): Imagine you are processing test scores out of 100, but some glitch caused a few scores to be recorded as 105.

scores = np.array([85, 92, 105, 78, 110, 95])

# "If score > 100, make it 100. Otherwise, leave it alone."
clean_scores = np.where(scores > 100, 100, scores)

print(clean_scores)
# Output: [ 85  92 100  78 100  95]

[ 85  92 100  78 100  95]


In [121]:
# Binary Classification: You have an array of model predictions (probabilities between 0 and 1) and you need to convert them into 1 (True) or 0 (False).

probabilities = np.array([0.1, 0.8, 0.4, 0.9, 0.51])

# "If prob >= 0.5, it's a 1. Otherwise, it's a 0."
predictions = np.where(probabilities >= 0.5, 1, 0)

print(predictions)
# Output: [0 1 0 1 1]

[0 1 0 1 1]


In [120]:
# Replacing Specific Values (Handling Errors): Sometimes datasets use -1 to represent missing data. You want to replace them with 0.
data = np.array([45, 62, -1, 55, -1, 80])

# "If data equals -1, change to 0. Otherwise, keep data."
fixed_data = np.where(data == -1, 0, data)

print(fixed_data)
# Output: [45 62  0 55  0 80]

[45 62  0 55  0 80]


### `np.argmax`

The most common mistake beginners make is thinking argmax() returns the actual maximum number.
- `np.max()` asks: "What is the highest score?"
- `np.argmax()` asks: "Who got the highest score?" (It points to the location).

To actually get the highest value using `argmax`, you would pass that index back into the array: `highest_value = a[np.argmax(a)]`.

In [137]:
a = np.array([33, 75, 18, 14, 69, 10, 69, 39, 98, 7])
print(a)

# ---------------------------------------------------------
# 1D Array argmax/argmin
# ---------------------------------------------------------
# np.argmax() returns the INDEX of the highest value, not the value itself.
# In our example, the highest value is 98, which is at index 8.
print(np.argmax(a)) 

# np.argmin() returns the INDEX of the lowest value.
# The lowest value is 7, which is at index 9.
print(np.argmin(a)) 

[33 75 18 14 69 10 69 39 98  7]
8
9


In [138]:
# ---------------------------------------------------------
# 2D Array argmax/argmin (Assuming the arr2D shown above)
# ---------------------------------------------------------

# axis=0 means "look down the columns" (compare rows).
print(np.argmax(arr2D, axis=0)) 

# axis=1 means "look across the rows" (compare columns).
print(np.argmax(arr2D, axis=1)) 

[2 2 0 1]
[2 3 0]


In [139]:
# Same logic applies for argmin, but finding the lowest values.
# Look down columns: 
print(np.argmin(arr2D, axis=0)) 

# Look across rows: 
print(np.argmin(arr2D, axis=1)) 

[0 0 1 2]
[1 2 3]


In [140]:
# Machine Learning Predictions (Classification)
# When a neural network makes a prediction, it usually outputs an array of probabilities for each category. argmax is the standard way to find out which category the model is most confident about.

# Imagine a model predicting if an image is a [Cat, Dog, Bird]
# It outputs these probabilities:
probabilities = np.array([0.15, 0.80, 0.05])

categories = ["Cat", "Dog", "Bird"]

# Find the index of the highest probability
predicted_index = np.argmax(probabilities)

print(f"The model predicts: {categories[predicted_index]}")
# Output: The model predicts: Dog

The model predicts: Dog


In [141]:
# Data Analysis (Finding the "When" or "Where")
# If you have time-series data, you often want to know when the peak or valley occurred, not just what the value was.

# Monthly sales data for a year (Jan to Dec)
sales = np.array([120, 150, 110, 200, 250, 300, 280, 210, 180, 400, 350, 390])
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

# Find out WHICH month had the worst sales
worst_month_index = np.argmin(sales)

print(f"Worst sales were in {months[worst_month_index]} with {sales[worst_month_index]} units.")
# Output: Worst sales were in Mar with 110 units.

Worst sales were in Mar with 110 units.


### `np.isin`

`np.isin` is one of the most powerful filtering tools in NumPy. Instead of writing nested `for loops` to check if items in one massive list exist in another massive list, np.isin() handles it instantly using vectorized C-code under the hood.

The resulting [False, True, False...] array is called a **Boolean Mask**. You overlay this mask onto any array of the same shape to filter it.

In [189]:
# Let's define 'a' as an array of the exact same length as 'b' (5 elements).
# Imagine 'a' is a list of customer names, and 'b' is their ID numbers.
a = np.array(["Alice", "Bob", "Charlie", "David", "Eve"])
b = np.array([10, 20, 30, 40, 50])

# This is the list we want to check against (e.g., a list of VIP IDs)
c = np.array([20, 40, 60])

# ---------------------------------------------------------
# Step 1: The Boolean Mask
# ---------------------------------------------------------
# np.isin() goes through every single element in 'b' and asks: 
# "Is this number anywhere inside 'c'?"
# It returns an array of True/False values matching the length of 'b'.
# 10 (No), 20 (Yes), 30 (No), 40 (Yes), 50 (No)
mask = np.isin(b, c)

print(mask) 
# Output: [False  True False  True False]

[False  True False  True False]


In [190]:
# ---------------------------------------------------------
# Step 2: Boolean Indexing (Filtering)
# ---------------------------------------------------------
# By placing the True/False mask inside the brackets of 'a', 
# NumPy acts like a filter. It only keeps the items in 'a' where the mask is True.
# Since the mask is True at index 1 and index 3, it grabs "Bob" and "David".
filtered_a = a[mask]

print(filtered_a)
# Output: ['Bob' 'David']

['Bob' 'David']


In [191]:
# Filtering a dataset based on a specific target list
# Imagine you are cleaning a massive Kaggle dataset or pulling reservation data from a flight database. You have an array of millions of transactions, but you only want to analyze the ones that belong to three specific regions.

# Array of 100,000 transaction region codes
transaction_regions = np.array(["EU", "US", "IN", "UK", "IN", "EU", "AU"]) # ... shortened for example

# We only want to analyze transactions from India, the US, and the UK
target_regions = ["IN", "US", "UK"]

# Create the mask and filter immediately
valid_transactions = transaction_regions[np.isin(transaction_regions, target_regions)]

print(valid_transactions)
# Output: ['US' 'IN' 'UK' 'IN']

['US' 'IN' 'UK' 'IN']


In [192]:
# Dropping unwanted data (The ~ NOT operator)
# You can easily reverse the behavior of np.isin() by putting a tilde (~) in front of it. This flips all the True values to False and vice versa, which is perfect for removing anomalies or blacklisted items.

product_ids = np.array([101, 102, 103, 104, 105])
discontinued_products = [102, 105]

# The '~' means "NOT in". Keep the products that are NOT discontinued.
active_products = product_ids[~np.isin(product_ids, discontinued_products)]

print(active_products)
# Output: [101 103 104]

[101 103 104]


## 🏋️ Practice Tasks
### 🟢 Easy
1. Replace all even numbers in an array with `-1`.
2. Find the index of the maximum value in a 1D array.

### 🟡 Medium
3. Find the indices of all values greater than 5 in a 2D array.
4. Check which elements of `[1, 2, 3, 4, 5]` are present in `[2, 4, 6]`.

### 🔴 Hard
5. Implement the **ReLU** activation function using `np.where`.
6. Find the indices of the **top 3 largest** values in an array (Hint: combine `argsort` and slicing).

## 🎤 Interview Question
**Q:** How do you implement the ReLU function (`max(0, x)`) in NumPy?
**A:** You can use `np.maximum(0, arr)` (fastest), or `np.where(arr > 0, arr, 0)`, or `arr * (arr > 0)`.

## 🌍 Real World Use Case
`np.where` is the exact mechanism Pandas uses under the hood for `df['col'].apply(lambda x: ...)` and `np.where` in SQL! It's also used to create binary masks in image processing.


In [13]:
# ==========================================
# 💻 CONCEPT 2: WHERE, ARGMAX, ISIN
# ==========================================
arr = np.array([1, -2, 3, -4, 5])

# Easy
print("Replace even with -1:", np.where(arr % 2 == 0, -1, arr))
print("Index of max:", np.argmax(arr))

# Medium
mat = np.array([[1, 6, 3], [8, 2, 9]])
rows, cols = np.where(mat > 5)
print(f"\nIndices > 5 -> Rows: {rows}, Cols: {cols}")

print("isin check:", np.isin([1, 2, 3, 4, 5], [2, 4, 6]))

# Hard: ReLU & Top 3
print("\nReLU:", np.where(arr > 0, arr, 0))

data = np.array([10, 50, 30, 90, 40, 80, 20])
# argsort gives indices that would sort the array. We take the last 3 and reverse them.
top_3_indices = np.argsort(data)[-3:][::-1]
print(f"Top 3 indices: {top_3_indices} -> Values: {data[top_3_indices]}")


Replace even with -1: [ 1 -1  3 -1  5]
Index of max: 4

Indices > 5 -> Rows: [0 1 1], Cols: [1 0 2]
isin check: [False  True False  True False]

ReLU: [1 0 3 0 5]
Top 3 indices: [3 5 1] -> Values: [90 80 50]


# 🧩 Concept 3: Joining, Modifying & Reshaping

## 📝 Theory
- **`np.concatenate()`**: Joins a sequence of arrays along an existing axis.
- **`np.append()`**: Appends values to the end of an array. (Warning: flattens if axis is not specified!).
- **`np.delete()`**: Removes elements at specified indices.
- **`np.put()`**: Replaces specific elements *in-place* using flattened indices.
- **`np.expand_dims()`**: Adds a new axis (shape `(N,)` → `(1, N)`).
- **`np.flip()`**: Reverses the order of elements along an axis.
- **`np.tile()` / `np.repeat()`**: Constructs an array by repeating A the number of times given by reps.
- **`np.swapaxes`**

## 📊 Visual Diagram
```text
expand_dims:
[1, 2, 3]  (shape: 3,)
   ↓ axis=0
[[1, 2, 3]] (shape: 1, 3)

flip:
[[1, 2],   ↓ flip(axis=1)   [[2, 1],
 [3, 4]]                      [4, 3]]
```

## ⚠️ Common Mistake
Using `np.append()` inside a `for` loop to build an array. 
**Why?** NumPy arrays are fixed in memory. `append` creates a brand new array and copies all data every single time, resulting in **O(N²)** time complexity! Always pre-allocate or use Python lists for loops, then convert to NumPy.



### `np.concatenate`

In [85]:
# axis=0 means "concatenate along the rows" (stacking vertically). 
# This places the original arr2D on top, and stacks the sorted version directly underneath it.
# If arr2D had 3 rows and 4 columns, 'result' will now have 6 rows and 4 columns.
result = np.concatenate((arr2D, np.sort(arr2D)), axis=0)
print(result)

[[11  1 13 11]
 [11 11  4 13]
 [16 13  9  1]
 [ 1 11 11 13]
 [ 4 11 11 13]
 [ 1  9 13 16]]


In [86]:
# axis=1 means "concatenate along the columns" (stacking horizontally).
# This places the original arr2D on the left, and glues the sorted version to its right side.
# If arr2D had 3 rows and 4 columns, 'result' will now have 3 rows and 8 columns.
result = np.concatenate((arr2D, np.sort(arr2D)), axis=1)
print(result)

[[11  1 13 11  1 11 11 13]
 [11 11  4 13  4 11 11 13]
 [16 13  9  1  1  9 13 16]]


In [89]:
# axis=0: Concatenating along the blocks (the "pages"). 
# This takes the "pages" from the sorted 3D array and adds them to the back of the original array.
# The number of rows and columns stays the same, but the total number of blocks doubles.
stacked_vertically = np.concatenate((arr3D, np.sort(arr3D)), axis=0)
print(stacked_vertically)

[[[5 1 1 9]
  [7 9 6 6]
  [5 1 8 1]]

 [[4 5 5 4]
  [5 2 7 1]
  [7 6 3 3]]

 [[1 1 5 9]
  [6 6 7 9]
  [1 1 5 8]]

 [[4 4 5 5]
  [1 2 5 7]
  [3 3 6 7]]]


In [92]:
# axis=1: Concatenating along the rows (on each individual page).
# For every single block/page, this takes the rows from the sorted version and 
# adds them to the bottom of the original rows. The number of blocks stays the same, 
# but each block now has twice as many rows.
stacked_horizontally = np.concatenate((arr3D, np.sort(arr3D)), axis=1)
print(stacked_horizontally)

[[[5 1 1 9]
  [7 9 6 6]
  [5 1 8 1]
  [1 1 5 9]
  [6 6 7 9]
  [1 1 5 8]]

 [[4 5 5 4]
  [5 2 7 1]
  [7 6 3 3]
  [4 4 5 5]
  [1 2 5 7]
  [3 3 6 7]]]


In [93]:
# axis=2: Concatenating along the columns (on each individual page).
# For every block/page, this takes the columns from the sorted version and 
# glues them to the right side of the original columns. Each block now has twice as many columns.
stacked_depth = np.concatenate((arr3D, np.sort(arr3D)), axis=2)
print(stacked_depth)

[[[5 1 1 9 1 1 5 9]
  [7 9 6 6 6 6 7 9]
  [5 1 8 1 1 1 5 8]]

 [[4 5 5 4 4 4 5 5]
  [5 2 7 1 1 2 5 7]
  [7 6 3 3 3 3 6 7]]]


### `np.append`
When appending arrays together along a specific axis, their dimensions must match on the other axes. By using arr2D.shape[0], this code cleverly ensures that the newly generated column has the exact same number of rows as the original matrix, preventing a common NumPy shape mismatch error.


In [68]:
# Examples of append

# 1. Appending to a 1D array
# This adds the value 200 to the end of 'arr1D'. 
# Note: np.append does NOT modify the original array in place; it returns a new array.
# To keep the result, you would need to assign it to a variable, e.g., arr1D = np.append(arr1D, 200)
np.append(arr1D, 200)

array([  4,   8,   5,   4,   7,   5,   5,   5,   2,   1,   7,   3,   4,
         4,   1,   2,   6,   5,   2,   8, 200])

In [67]:
# 2. Appending a column of 1s to a 2D array
print(np.append(
    arr2D,                               # The original 2D array
    np.ones((arr2D.shape[0], 1)),        # Creates a new 2D array of 1s. 
                                         # 'arr2D.shape[0]' ensures it has the exact same number of rows as arr2D, and '1' gives it a single column.
    axis=1                               # axis=1 tells NumPy to append horizontally (adding a new column). axis=0 would append a new row.
))

[[11.  1. 13. 11.  1.]
 [11. 11.  4. 13.  1.]
 [16. 13.  9.  1.  1.]]


In [ ]:
# 3. Appending two columns of random numbers to a 2D array
print(np.append(
    arr2D,                               # The original 2D array
    np.random.random((arr2D.shape[0], 2)), # Creates a new 2D array filled with random floats between 0.0 and 1.0. 
                                         # Again, the shape matches the number of rows of arr2D and adds 2 columns.
    axis=1                               # Appends this new random column horizontally to the right side of arr2D.
))

[[11.          1.         13.         11.          0.63753967  0.84021391]
 [11.         11.          4.         13.          0.24324144  0.37496701]
 [16.         13.          9.          1.          0.57568341  0.3928707 ]]


In [71]:

# 1. Create the original 3D array using randint
# Let's imagine this as 2 separate blocks, where each block is a 3x4 grid.
# Shape: (2, 3, 4) -> (blocks/depth, rows, columns)
arr3D = np.random.randint(1, 10, size=(2, 3, 4))

# --- THE CRITICAL STEP ---
# We upgrade the 2D array to 3D. 
# np.expand_dims adds a new axis. By choosing axis=0, we change the 
# shape from (3, 4) to (1, 3, 4). It is now technically a 3D array containing one block.
arr2D_expanded = np.expand_dims(arr2D, axis=0)

# 3. Now we can safely append them together
result = np.append(
    arr3D,           # The original 3D array
    arr2D_expanded,  # The 2D array we just converted to 3D
    axis=0           # axis=0 means we are adding a new 'block' to the depth stack
)

print(f"Original 3D shape: {arr3D.shape}")
print(f"Original 2D shape: {arr2D.shape}")
print(f"Expanded 2D shape: {arr2D_expanded.shape}")
print(f"Final Appended shape: {result.shape}")

Original 3D shape: (2, 3, 4)
Original 2D shape: (3, 4)
Expanded 2D shape: (1, 3, 4)
Final Appended shape: (3, 3, 4)


### `np.expand_dims`

In [101]:

#  Expanding along axis=0 (Adding a "Row" dimension)
# axis=0 inserts a new dimension at the very beginning (index 0).
# This effectively wraps your entire 1D array inside a new set of brackets, 
# turning it into a 2D "row vector".
print(np.expand_dims(arr1D, axis=0), np.expand_dims(arr1D, axis=0).shape)

[[4 8 5 4 7 5 5 5 2 1 7 3 4 4 1 2 6 5 2 8]] (1, 20)


In [102]:
# Expanding along axis=1 (Adding a "Column" dimension)
# axis=1 inserts a new dimension at the second position (index 1).
# This wraps *each individual element* in its own set of brackets, 
# turning it into a 2D "column vector".
print(np.expand_dims(arr1D, axis=1), np.expand_dims(arr1D, axis=1).shape)

[[4]
 [8]
 [5]
 [4]
 [7]
 [5]
 [5]
 [5]
 [2]
 [1]
 [7]
 [3]
 [4]
 [4]
 [1]
 [2]
 [6]
 [5]
 [2]
 [8]] (20, 1)


> `np.expand_dims`
- **What it does**: It only does one thing: it inserts a "dummy" dimension (a dimension of length 1) at a specific axis.
- **Why/When to use it**: Use this when you want to increase the dimensionality of an array without changing its fundamental structure, and especially when you don't know (or **don't want to calculate) the original shape**.
- **Common Use Case**: In machine learning, models often expect data in batches. If you have a single image shaped (`28, 28`), you can use `np.expand_dims(image, axis=0)` to instantly turn it into (1, 28, 28)—a batch of one image—without needing to manually type `28, 28`.
> `np.reshape`
- **What it does**: It completely restructures the data into a brand new shape, as long as the total number of elements remains the same.
- **Why/When to use it**: Use this when you are fundamentally reorganizing your data, such as turning a long 1D list into a 2D matrix, or flattening a 3D array into 1D.
- Common Use Case: If you have 12 data points in a 1D array and you want to organize them into a calendar view of 3 weeks (rows) with 4 days (columns).
*Note: You can use `np.reshape(arr1D, (1, -1))` to mimic what `expand_dims` does, but `expand_dims` is considered much more readable and explicit when your specific goal is just to add a single dimension*.

> Practical Examples of Both
Using `np.expand_dims` to prep data for a machine learning model:


In [106]:
# A single color image (Height, Width, Color Channels)
single_image = np.random.randint(0, 255, size=(256, 256, 3))

# Neural networks usually expect (Batch Size, Height, Width, Channels)
# We easily add a batch dimension to the front
batch_ready_image = np.expand_dims(single_image, axis=0)

print(batch_ready_image.shape) 

(1, 256, 256, 3)


In [107]:
# A flat array of 12 numbers
flat_data = np.arange(12) 

# Reorganize it into a 3x4 matrix
matrix_data = np.reshape(flat_data, (3, 4))

print(matrix_data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [196]:
# ---------------------------------------------------------
# 1D Array Flipping
# ---------------------------------------------------------
print(arr1D)

# np.flip() simply reverses the order of the elements.
print(np.flip(arr1D))


[ 2  8  4  9  5 12]
[12  5  9  4  8  2]


In [197]:
# ---------------------------------------------------------
# 2D Array Flipping (The Default Behavior)
# ---------------------------------------------------------
print(arr2D)

# When you use np.flip() on a 2D array WITHOUT specifying an axis, 
# it flips the data along ALL axes simultaneously. 
# It flips it upside down (rows) AND backwards (columns).
print(np.flip(arr2D))

[[11  1 13 11]
 [11 11  4 13]
 [16 13  9  1]]
[[ 1  9 13 16]
 [13  4 11 11]
 [11 13  1 11]]


### `np.put(array, indices, new_values)`

In [201]:
print("Original:", arr1D)

# ---------------------------------------------------------
# np.put: Replacing values at specific locations
# ---------------------------------------------------------
# Syntax: np.put(array, indices, new_values)
#   - array: The array you want to change.
#   - indices: The exact positions you want to overwrite ([0, 1] means the 1st and 2nd items).
#   - new_values: The numbers you want to put there instead ([2, 3]).
np.put(arr1D, [0, 1], [2, 3])

# Notice that we DO NOT do: result = np.put(...)
# This is because np.put modifies the original array permanently.
print("Modified:", arr1D)


Original: [ 2  8  4  9  5 12]
Modified: [ 2  3  4  9  5 12]


### `np.del()`

In [202]:
print("Original array:", a)

# ---------------------------------------------------------
# 1D Array: Deleting by Index
# ---------------------------------------------------------
# np.delete(array, indices_to_remove)
# It looks at the INDEX positions, not the actual values.
# Index 3 is the number '40'. Index 4 is the number '50'.
result = np.delete(a, [3, 4])

print("After deletion:", result)

# IMPORTANT: Notice that 'a' itself has NOT changed. 
# np.delete creates a brand new array.
print("Original is unharmed:", a)
# Output: [10 20 30 40 50 60]

Original array: ['Alice' 'Bob' 'Charlie' 'David' 'Eve']
After deletion: ['Alice' 'Bob' 'Charlie']
Original is unharmed: ['Alice' 'Bob' 'Charlie' 'David' 'Eve']


In [203]:
# ---------------------------------------------------------
# 2D Array: Deleting Rows or Columns
# ---------------------------------------------------------
arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

# Delete Row 1 (the middle row) using axis=0
no_middle_row = np.delete(arr2D, 1, axis=0)
print("\nDeleted Row 1:\n", no_middle_row)

# Delete Column 0 and Column 2 using axis=1
middle_col_only = np.delete(arr2D, [0, 2], axis=1)
print("\nDeleted Cols 0 and 2:\n", middle_col_only)



Deleted Row 1:
 [[1 2 3]
 [7 8 9]]

Deleted Cols 0 and 2:
 [[2]
 [5]
 [8]]


### `np.swapaxes`

`np.swapaxes()` interchanges two specified axes of an array without copying data (it returns a view when possible). This is crucial for reshaping data to match algorithm expectations.

- **Does NOT create a copy by default** (returns a view when strides allow)
- **Key difference from transpose**: `transpose()` reverses ALL axes; `swapaxes()` swaps only two
- **Common in image processing**: Changing from (height, width, channels) to (channels, height, width)


In [222]:
# Sample 3D array (2 blocks, 3 rows, 4 columns)
arr3D = np.arange(24).reshape(2, 3, 4)
print("Original shape:", arr3D.shape)  # (2, 3, 4)
print("Original:\n", arr3D)

# ---------------------------------------------------------
# np.swapaxes: Swap any two axes of an array
# ---------------------------------------------------------
# Syntax: np.swapaxes(array, axis1, axis2)
# Swaps axis 0 (depth) with axis 1 (rows)
# Shape changes from (2, 3, 4) to (3, 2, 4)
swapped = np.swapaxes(arr3D, 0, 1)

print("\nSwapped shape:", swapped.shape)  # (3, 2, 4)
print("Swapped (axes 0 and 1):\n", swapped)

# Swapping axes 1 and 2: (2, 3, 4) -> (2, 4, 3)
swapped2 = np.swapaxes(arr3D, 1, 2)
print("\nSwapped shape (axes 1,2):", swapped2.shape)  # (2, 4, 3)


Original shape: (2, 3, 4)
Original:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Swapped shape: (3, 2, 4)
Swapped (axes 0 and 1):
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

Swapped shape (axes 1,2): (2, 4, 3)


In [223]:
# Image Channel Reordering

# Image in format (height, width, channels) - OpenCV style
image_cv = np.random.randint(0, 256, (480, 640, 3))  # HWC format

# Convert to (channels, height, width) - PyTorch/TensorFlow style
image_torch = np.swapaxes(np.swapaxes(image_cv, 0, 2), 1, 2)
# Or simply: image_torch = image_cv.transpose(2, 0, 1)
print("PyTorch shape:", image_torch.shape)  # (3, 480, 640)


PyTorch shape: (3, 480, 640)


In [224]:
# Batch Matrix Transpose

# Batch of 10 matrices, each 4x4
batch = np.random.randn(10, 4, 4)

# Transpose each matrix individually (swap last two axes)
transposed_batch = np.swapaxes(batch, 1, 2)
print("Each matrix transposed:", transposed_batch.shape)  # (10, 4, 4)


Each matrix transposed: (10, 4, 4)


## 🏋️ Practice Tasks
### 🟢 Easy
1. Concatenate two 1D arrays.
2. Add a new axis to a 1D array to make it a column vector.

### 🟡 Medium
3. Delete the 2nd row from a 2D array.
4. Flip a 2D array horizontally (reverse columns).

### 🔴 Hard
5. Use `np.put` to replace the diagonal elements of a 3x3 matrix with `99`.
6. Explain the difference between `np.tile([1,2], 3)` and `np.repeat([1,2], 3)`.

## 🎤 Interview Question
**Q:** What is the difference between `np.tile` and `np.repeat`?
**A:** 
- `np.tile([1, 2], 3)` repeats the *whole array*: `[1, 2, 1, 2, 1, 2]`
- `np.repeat([1, 2], 3)` repeats *each element*: `[1, 1, 1, 2, 2, 2]`


In [14]:
# ==========================================
# 💻 CONCEPT 3: JOINING & MODIFYING
# ==========================================
a = np.array([1, 2])
b = np.array([3, 4])

# Easy
print("Concatenate:", np.concatenate([a, b]))
col_vec = np.expand_dims(a, axis=1)
print("Column vector shape:", col_vec.shape)

# Medium
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nDelete row 1:\n", np.delete(mat, 1, axis=0))
print("Flip horizontally:\n", np.flip(mat, axis=1))

# Hard: np.put
mat_3x3 = np.zeros((3, 3), dtype=int)
# Diagonal indices in flattened 3x3 are 0, 4, 8
np.put(mat_3x3, [0, 4, 8], [99, 99, 99])
print("\nMatrix with put diagonal:\n", mat_3x3)

# Tile vs Repeat
print("\nTile:", np.tile([1, 2], 3))
print("Repeat:", np.repeat([1, 2], 3))


Concatenate: [1 2 3 4]
Column vector shape: (2, 1)

Delete row 1:
 [[1 2 3]
 [7 8 9]]
Flip horizontally:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]

Matrix with put diagonal:
 [[99  0  0]
 [ 0 99  0]
 [ 0  0 99]]

Tile: [1 2 1 2 1 2]
Repeat: [1 1 1 2 2 2]


# 📈 Concept 4: Cumulative Math & Statistics

## 📝 Theory
- **`np.cumsum()` / `np.cumprod()`**: Returns the cumulative sum/product. Essential for calculating running totals or probability distributions.
- **`np.percentile()`**: Computes the nth percentile (e.g., median is 50th, quartiles are 25th/75th).
- **`np.histogram()`**: Computes the frequency distribution of data (doesn't plot it, just returns bins and counts!).
- **`np.corrcoef()`**: Returns the Pearson correlation matrix.
- **`np.count_nonzero()`**: Counts how many elements evaluate to True (or are non-zero).

## 📊 Visual Diagram
```text
Array:    [1, 2, 3, 4]
cumsum:   [1, 3, 6, 10]  (1, 1+2, 1+2+3, 1+2+3+4)

Histogram:
Data: [1, 1, 2, 3, 3, 3, 4]
Bins: [1, 2, 3, 4]
Counts: [2, 1, 3, 1]
```

## ⚠️ Common Mistake
Thinking `np.histogram()` draws a plot. It **only calculates the math** (returns `counts` and `bin_edges`). You must pass these to `plt.bar()` or `plt.hist()` to visualize it!



### `np.cumsum` & `cumprod`

- `np.cumsum` (Cumulative Sum): Think of this as a running total. Instead of just giving you the final sum, it gives you an array showing the sum at every single step.
- `np.cumprod` (Cumulative Product): The exact same concept as cumsum, but it multiplies the numbers instead of adding them.
- `np.prod` (Product): This multiplies all elements together but only returns the final result, not the step-by-step array.

*Note: If you run `np.cumsum(arr2D)` without specifying an axis, NumPy will flatten your 2D array into a 1D line first, and then calculate the running total.*

In [160]:
# ---------------------------------------------------------
# 1D Array: Cumulative Sum and Total Product
# ---------------------------------------------------------
# np.cumsum(): Keeps a "running total" as it moves through the array.
# np.prod(): Multiplies EVERY number in the array together into a single value.
print(arr1D, np.cumsum(arr1D), np.prod(arr1D), sep="\n")

[ 2  8  4  9  5 12]
[ 2 10 14 23 28 40]
34560


In [161]:
# ---------------------------------------------------------
# 2D Array: axis=0 (Looking Down the Columns)
# ---------------------------------------------------------
# axis=0 applies the logic vertically (column by column).
# np.cumsum(arr2D, axis=0): Running total down the columns.
# np.cumprod(arr2D, axis=0): Running multiplication down the columns.
print(arr2D, np.cumsum(arr2D, axis=0), np.cumprod(arr2D, axis=0), sep="\n")

[[11  1 13 11]
 [11 11  4 13]
 [16 13  9  1]]
[[11  1 13 11]
 [22 12 17 24]
 [38 25 26 25]]
[[  11    1   13   11]
 [ 121   11   52  143]
 [1936  143  468  143]]


In [162]:
# ---------------------------------------------------------
# 2D Array: axis=1 (Looking Across the Rows)
# ---------------------------------------------------------
# axis=1 applies the logic horizontally (row by row).
# np.cumsum(arr2D, axis=1): Running total across each row.
# np.cumprod(arr2D, axis=1): Running multiplication across each row.
print(arr2D, np.cumsum(arr2D, axis=1), np.cumprod(arr2D, axis=1), sep="\n")

[[11  1 13 11]
 [11 11  4 13]
 [16 13  9  1]]
[[11 12 25 36]
 [11 22 26 39]
 [16 29 38 39]]
[[  11   11  143 1573]
 [  11  121  484 6292]
 [  16  208 1872 1872]]


In [153]:
# Finance (Running Totals / Year-to-Date)
# If you have an array representing monthly profits, cumsum instantly gives you your Year-to-Date (YTD) total at each month.

# Profits for Jan, Feb, Mar, Apr
monthly_profits = np.array([1000, 1500, -500, 2000])

# Calculate Year-to-Date total at each step
ytd_profits = np.cumsum(monthly_profits)

print(ytd_profits)
# Output: [1000 2500 2000 4000]
# By April, the total profit was 4000.

[1000 2500 2000 4000]


In [154]:
# Statistics (Cumulative Distribution Function - CDF)
# In probability, if you have an array of percentages representing how likely an event is to happen at different stages, cumsum helps you find the probability that the event will happen by a certain stage.

# Daily probability of a machine breaking down (Day 1, Day 2, Day 3)
daily_prob = np.array([0.10, 0.15, 0.05])

# Probability it has broken down BY that day
cumulative_prob = np.cumsum(daily_prob)

print(cumulative_prob)
# Output: [0.10 0.25 0.30]
# There is a 25% chance it breaks down by the end of Day 2.

[0.1  0.25 0.3 ]


In [163]:
# For Compound Interest or Investment Growth
# If you have an array representing the daily or yearly growth multiplier of a stock, cumprod shows you the total value of your investment over time.

# A stock grows by 5% (1.05), drops by 2% (0.98), grows by 10% (1.10)
daily_multipliers = np.array([1.05, 0.98, 1.10])
initial_investment = 1000

# Calculate the growth journey
value_over_time = initial_investment * np.cumprod(daily_multipliers)

print(value_over_time)
# Output: [1050.   1029.   1131.9]

[1050.  1029.  1131.9]


In [165]:
# For Calculating Probabilities
# If you have a series of independent events and you want to know the probability of ALL of them happening, you multiply their probabilities together.

# The chances of 4 specific things happening in a row
probabilities = np.array([0.5, 0.8, 0.9, 0.2])

# Chance of all of them happening
chance_of_all = np.prod(probabilities)

print(chance_of_all)
# Output: 0.072 (or 7.2%)

0.07200000000000001


### `np.percentile` & `np.median`


In [ ]:
# ---------------------------------------------------------
# np.percentile: "What score beats X% of the data?"
# ---------------------------------------------------------
# Syntax: np.percentile(array, percentage)
# This calculates the 75th percentile. It finds the value where 
# exactly 75% of the numbers in the array are lower than it, 
# and 25% are higher. 
print(np.percentile(arr1D, 75))

8.75


In [170]:
# ---------------------------------------------------------
# np.median: "What is the exact middle value?"
# ---------------------------------------------------------
# The median is the exact center of your sorted data.
# It is mathematically identical to the 50th percentile: np.percentile(arr1D, 50).
# Half the scores are below 80, and half the scores are above 80.
# Output: 80.0
print(np.median(arr1D))

6.5


In [172]:
# Standardized Testing and Grading
# When you take the SATs, your raw score matters less than your percentile.

scores = np.array([500, 850, 1100, 1250, 1400, 1550])

# "What score do I need to be in the top 10%?"
# (Meaning you want the 90th percentile cutoff)
top_10_cutoff = np.percentile(scores, 90)

print(f"To be in the top 10%, you need a score of {top_10_cutoff}")

To be in the top 10%, you need a score of 1475.0


In [173]:
# Web Server Performance (The "P99" metric)
# If you work in software engineering, companies rarely care about the average time it takes a website to load. Instead, they look at the 99th percentile (P99).

# The time (in milliseconds) it took for 1000 users to load a webpage
load_times = np.random.randint(50, 800, size=1000)

p99 = np.percentile(load_times, 99)

print(f"99% of our users load the site in under {p99} ms.")
# If this number is too high, engineers know they need to fix something 
# because the slowest 1% of users are having a terrible experience.

99% of our users load the site in under 788.01 ms.


### `np.histogram` & `np.corrcoef`

The biggest misconception is that `np.histogram` function plots a chart. It does not. It takes a messy array of continuous numbers and sorts them into discrete buckets (bins). It returns two arrays:
1. **Counts**: The number of items that fell into each bucket.
2. **Bin Edges**: The boundaries of those buckets.

`np.corrcoef` measures the linear relationship between two variables using the Pearson correlation formula. The resulting number always falls between -1.0 and 1.0:
1. **1.0**: Perfect positive correlation (As X goes up, Y goes up identically).
2. **0.0**: Absolutely no relationship (Random scatter).
3. **-1.0**: Perfect negative correlation (As X goes up, Y goes down identically).

*Note on the Matrix Output: When you pass two arrays to `np.corrcoef(x, y)`, it returns a 2x2 grid. The top-left and bottom-right will always be `1.0` (because X correlates perfectly with itself, and Y correlates perfectly with itself). The other two numbers are the actual relationship between X and Y.*

In [174]:
# ==========================================
# np.histogram: Counting data into "bins"
# ==========================================
# Let's say we have the ages of 10 people in a restaurant
ages = np.array([22, 25, 29, 35, 42, 45, 48, 55, 62, 70])

# np.histogram DOES NOT draw a picture. It does the math behind the picture.
# We tell it to group the ages into 3 equal-width "bins" (e.g., young, middle, older).
counts, bin_edges = np.histogram(ages, bins=3)

# 'counts' tells us HOW MANY people are in each bin.
print(f"Counts: {counts}") 
# 'bin_edges' tells us the start and end numbers for each bin.
# Note: There is always 1 more bin_edge than there are counts.
print(f"Bin Edges: {bin_edges}\n")

Counts: [4 3 3]
Bin Edges: [22. 38. 54. 70.]



In [175]:
# ==========================================
# np.corrcoef: Finding linear relationships
# ==========================================
# Let's look at the relationship between hours studied and test scores
hours_studied = np.array([1, 2, 3, 4, 5, 6])
test_scores =   np.array([50, 55, 65, 70, 85, 90])

# np.corrcoef returns a "Correlation Matrix".
correlation_matrix = np.corrcoef(hours_studied, test_scores)

print("Correlation Matrix:")
print(correlation_matrix)

# To get just the specific correlation number between the two variables, 
# you extract the number from row 0, column 1 (or row 1, column 0)
actual_correlation = correlation_matrix[0, 1]
print(f"\nThe correlation coefficient is: {actual_correlation:.3f}")

Correlation Matrix:
[[1.        0.9890738]
 [0.9890738 1.       ]]

The correlation coefficient is: 0.989


In [176]:
# For Image Processing (Exposure Check)
# Here, we simulate an "overexposed" image (mostly bright pixels) and use a histogram to detect that the highlights are blown out.

# 1. Simulate an overexposed 1080p image (1080 x 1920 pixels)
# We generate random pixel values, but heavily skew them towards 255 (white)
image_pixels = np.random.randint(200, 256, size=(1080, 1920))

# 2. Define our brightness buckets (bins)
# Bin 1: 0-85 (Shadows/Dark)
# Bin 2: 85-170 (Midtones)
# Bin 3: 170-255 (Highlights/Bright)
bins = [0, 85, 170, 255]

# 3. Run the histogram
counts, bin_edges = np.histogram(image_pixels, bins=bins)

shadows, midtones, highlights = counts

print(f"Shadow pixels: {shadows}")
print(f"Midtone pixels: {midtones}")
print(f"Highlight pixels: {highlights}")

# 4. The Algorithm Decision
total_pixels = image_pixels.size
if highlights / total_pixels > 0.8:
    print("\nSYSTEM ALERT: Image is overexposed! Triggering auto-darken algorithm...")

Shadow pixels: 0
Midtone pixels: 0
Highlight pixels: 2073600

SYSTEM ALERT: Image is overexposed! Triggering auto-darken algorithm...


In [177]:
# For Demographics Grouping
# Instead of a slow for loop to categorize 100,000 users, we use np.histogram with custom bin edges to instantly group them by birth year.

# 1. Simulate a database of 100,000 user birth years (between 1946 and 2012)
birth_years = np.random.randint(1946, 2013, size=100000)

# 2. Define the generation cutoffs (Bin edges)
# Boomers: 1946-1964
# Gen X: 1965-1980
# Millennials: 1981-1996
# Gen Z: 1997-2012
# Note: The last bin edge must be 2013 to include the year 2012.
generation_bins = [1946, 1965, 1981, 1997, 2013]

# 3. Run the histogram
counts, edges = np.histogram(birth_years, bins=generation_bins)

print("--- User Demographics ---")
print(f"Boomers:     {counts[0]:,}")
print(f"Gen X:       {counts[1]:,}")
print(f"Millennials: {counts[2]:,}")
print(f"Gen Z:       {counts[3]:,}")

--- User Demographics ---
Boomers:     28,337
Gen X:       24,021
Millennials: 23,959
Gen Z:       23,683


In [178]:
# For Stock Market Diversification
# Here, we compare a tech stock to two other stocks to see which one makes a better pair for a diversified portfolio.

# 1. Simulate 10 days of stock price movements
tech_stock   = np.array([100, 102, 105, 103, 108, 110, 115, 112, 120, 125])
semiconductor_stock = np.array([50, 51, 52, 51, 54, 55, 57, 56, 60, 62]) # Moves exactly like Tech
gold_etf     = np.array([200, 198, 195, 196, 190, 188, 185, 187, 180, 175]) # Moves opposite to Tech

# 2. Check correlation between Tech and Semiconductors
# We slice [0, 1] to get just the relationship number, ignoring the 1.0 self-correlations
tech_semi_corr = np.corrcoef(tech_stock, semiconductor_stock)[0, 1]

# 3. Check correlation between Tech and Gold
tech_gold_corr = np.corrcoef(tech_stock, gold_etf)[0, 1]

print(f"Correlation (Tech vs. Semiconductors): {tech_semi_corr:.2f}")
print(f"Correlation (Tech vs. Gold): {tech_gold_corr:.2f}")

print("\n--- Analyst Conclusion ---")
if tech_semi_corr > 0.8:
    print("Do not buy Semiconductors if you own Tech. They crash together.")
if tech_gold_corr < 0:
    print("Gold is a great hedge for your Tech stock. It acts as a safety net.")

Correlation (Tech vs. Semiconductors): 1.00
Correlation (Tech vs. Gold): -0.99

--- Analyst Conclusion ---
Do not buy Semiconductors if you own Tech. They crash together.
Gold is a great hedge for your Tech stock. It acts as a safety net.


In [179]:
# For ML Feature Selection
# When feeding data to an AI, you want to drop useless information so the model learns faster. Here is how you identify the "garbage" data.

# 1. Target Variable (What the AI is trying to predict)
house_prices = np.array([300000, 350000, 400000, 500000, 600000])

# 2. Potential Features (The data we might feed the AI)
square_footage = np.array([1500, 1800, 2200, 2800, 3500]) # Makes sense
owner_shoe_size = np.array([10, 8, 12, 7, 9]) # Absolute garbage data

# 3. Calculate correlations against the target
sqft_correlation = np.corrcoef(square_footage, house_prices)[0, 1]
shoe_size_correlation = np.corrcoef(owner_shoe_size, house_prices)[0, 1]

print(f"Square Footage Predictive Power: {sqft_correlation:.2f}")
print(f"Shoe Size Predictive Power: {shoe_size_correlation:.2f}")

print("\n--- Feature Selection Process ---")
# If the correlation is between -0.2 and 0.2, it's mostly noise.
if abs(sqft_correlation) > 0.2:
    print("[KEEP] 'Square Footage' added to AI training data.")
else:
    print("[DROP] 'Square Footage' is useless.")

if abs(shoe_size_correlation) < 0.2:
    print("[DROP] 'Owner Shoe Size' has no predictive power. Discarding to save compute.")
else:
    print("[KEEP] 'Owner Shoe Size' added to AI training data.")

Square Footage Predictive Power: 1.00
Shoe Size Predictive Power: -0.30

--- Feature Selection Process ---
[KEEP] 'Square Footage' added to AI training data.
[KEEP] 'Owner Shoe Size' added to AI training data.


## 🏋️ Practice Tasks
### 🟢 Easy
1. Calculate the cumulative sum of `[1, 2, 3, 4, 5]`.
2. Find the 50th percentile (median) of an array.

### 🟡 Medium
3. Calculate the correlation coefficient between two arrays: `X = [1, 2, 3, 4, 5]` and `Y = [2, 4, 5, 4, 5]`.
4. Count how many `True` values exist in a boolean mask.

### 🔴 Hard
5. Normalize an array to a probability distribution using `cumsum`.
6. Compute the histogram of 1000 random normal numbers with 10 bins.

## 🎤 Interview Question
**Q:** What does `np.corrcoef(x, y)` return?
**A:** It returns a **2x2 symmetric matrix**. The diagonal contains `1.0` (correlation of x with x, and y with y). The off-diagonal elements contain the actual Pearson correlation coefficient between `x` and `y`.


In [15]:
# ==========================================
# 💻 CONCEPT 4: CUMULATIVE & STATS
# ==========================================
arr = np.array([1, 2, 3, 4, 5])

# Easy
print("Cumsum:", np.cumsum(arr))
print("Median (50th %ile):", np.percentile(arr, 50))

# Medium
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])
corr_matrix = np.corrcoef(x, y)
print(f"\nCorrelation Matrix:\n{corr_matrix}")
print(f"Correlation between X and Y: {corr_matrix[0, 1]:.3f}")

mask = np.array([True, False, True, True, False])
print("Count non-zero (True):", np.count_nonzero(mask))

# Hard: Histogram
data = np.random.randn(1000)
counts, bins = np.histogram(data, bins=10)
print(f"\nHistogram Counts: {counts}")
print(f"Histogram Bins: {np.round(bins, 2)}")


Cumsum: [ 1  3  6 10 15]
Median (50th %ile): 3.0

Correlation Matrix:
[[1.         0.77459667]
 [0.77459667 1.        ]]
Correlation between X and Y: 0.775
Count non-zero (True): 3

Histogram Counts: [  2  13  50 116 240 253 199  82  34  11]
Histogram Bins: [-3.57 -2.89 -2.2  -1.52 -0.84 -0.16  0.53  1.21  1.89  2.57  3.25]


# 🧮 Concept 5: Set Operations, Clipping & Comparisons

## 📝 Theory
- **Set Operations**: `np.union1d`, `np.intersect1d`, `np.setdiff1d`, `np.setxor1d`. (Note: These flatten arrays and return **unique, sorted** results).
- **`np.clip(arr, min, max)`**: Limits values to a specific range. Values below `min` become `min`, above `max` become `max`.
- **`np.allclose(a, b)`**: Checks if two arrays are element-wise equal within a tolerance (crucial for floats!).
- **`np.array_equal(a, b)`**: Checks if two arrays have the same shape and exact elements.
- **`np.random.uniform(low, high, size)`**: Draws samples from a uniform distribution.

## 📊 Visual Diagram
```text
A = [1, 2, 3]
B = [3, 4, 5]

intersect1d: [3]
union1d:     [1, 2, 3, 4, 5]
setdiff1d(A,B): [1, 2] (In A but not B)

Clipping:
Input:  [-5, 0, 5, 10]
Clip(0, 5): [0, 0, 5, 5]
```

## ⚠️ Common Mistake
Using `==` to compare floating-point NumPy arrays. Due to precision issues (e.g., `0.1 + 0.2 != 0.3`), `==` will return `False`. **Always use `np.allclose()` for floats.**

In [210]:
# Sample arrays
setA = np.array([1, 2, 3, 4, 5])
setB = np.array([4, 5, 6, 7, 8])

# ---------------------------------------------------------
# 1. Union (Combine everything, remove duplicates)
# ---------------------------------------------------------
# Like a SQL FULL OUTER JOIN or UNION. It takes all items from both arrays.
# It automatically sorts the result and drops any duplicate numbers.
print(np.union1d(setA, setB))


# ---------------------------------------------------------
# 2. Intersection (Find the common ground)
# ---------------------------------------------------------
# Like a SQL INNER JOIN. It only returns the numbers that exist in BOTH arrays.
# The numbers 4 and 5 are the only ones present in both setA and setB.
print(np.intersect1d(setA, setB))


# ---------------------------------------------------------
# 3. Set Difference (Find what is missing)
# ---------------------------------------------------------
# Like a SQL EXCEPT or LEFT JOIN (where right is null). 
# It asks: "What is in setA that is NOT in setB?"
# It removes the 4 and 5 because they exist in setB. Order matters here!
print(np.setdiff1d(setA, setB))


# ---------------------------------------------------------
# 4. Set XOR / Symmetric Difference (Find the exclusives)
# ---------------------------------------------------------
# It asks: "What is in ONE of the arrays, but NOT both?"
# It drops the shared numbers (4 and 5) and keeps the unique ones from both sides.
print(np.setxor1d(setA, setB))




[1 2 3 4 5 6 7 8]
[4 5]
[1 2 3]
[1 2 3 6 7 8]


In [211]:
# To find overlapping customers
# You want to run a targeted marketing campaign for high-value customers who buy both electronics and clothing.

electronics_buyers = np.array([101, 105, 202, 305, 400])
clothing_buyers = np.array([202, 300, 400, 500])

# Find customers who bought from BOTH categories
cross_shoppers = np.intersect1d(electronics_buyers, clothing_buyers)

print(f"Send promo codes to Customer IDs: {cross_shoppers}")
# Output: Send promo codes to Customer IDs: [202 400]

Send promo codes to Customer IDs: [202 400]


In [213]:
# To find churned or inactive users
# You have a list of everyone who registered for a service, and a list of everyone who logged in this month. You want to find out exactly who is inactive.
    
registered_users = np.array([1, 2, 3, 4, 5, 6])
logged_in_this_month = np.array([2, 4, 6])

# Find users who are in the registered list, but NOT in the active list
inactive_users = np.setdiff1d(registered_users, logged_in_this_month)

print(f"Trigger re-engagement emails to IDs: {inactive_users}")
# Output: Trigger re-engagement emails to IDs: [1 3 5]

Trigger re-engagement emails to IDs: [1 3 5]


In [214]:
# To merge datasets without duplicating rows
# You are migrating data from an old system to a new system. Some users are in both systems. If you just append the arrays, you will create duplicate accounts. Using a union prevents this.

old_system_ids = np.array([10, 20, 30, 40])
new_system_ids = np.array([30, 40, 50, 60])

# Combine them safely. The overlaps (30, 40) are only counted once.
master_database = np.union1d(old_system_ids, new_system_ids)

print(master_database)
# Output: [10 20 30 40 50 60]

[10 20 30 40 50 60]


### `np.clip(array, min, max)`

`np.clip()` is a fast, vectorized way to apply both a floor (minimum limit) and a ceiling (maximum limit) to your data simultaneously.
1. You don't need both: If you only want to set a floor but don't care about a ceiling, you can pass `None` as the max value: `np.clip(arr1D, 3, None)`.
2. It creates a copy: Like most NumPy functions, it returns a brand new array and leaves the original untouched.

*Note: You could achieve the exact same result using `np.where(arr1D < 3, 3, np.where(arr1D > 6, 6, arr1D))`, but `np.clip` is vastly cleaner and faster.*

In [217]:
arr1D = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Original:", arr1D)

# ---------------------------------------------------------
# np.clip: Setting boundaries (Floors and Ceilings)
# ---------------------------------------------------------
# Syntax: np.clip(array, min_value, max_value)
# It forces all numbers in the array to stay within the range [3, 6].
# - Any number smaller than 3 is bumped UP to 3.
# - Any number larger than 6 is pulled DOWN to 6.
# - Numbers already between 3 and 6 are left alone.
clipped_arr = np.clip(arr1D, 3, 6)

print("Clipped: ", clipped_arr)


Original: [1 2 3 4 5 6 7 8]
Clipped:  [3 3 3 4 5 6 6 6]


In [218]:
# Image Processing (Pixel Boundaries)
# As we've established, images are arrays of pixel values that must stay between 0 (pitch black) and 255 (pure white). If you apply a brightening algorithm that adds 50 to every pixel, a pixel that was already at 220 will become 270. This will crash image software.

# A slightly bright image
pixels = np.array([150, 200, 220, 240])

# Brighten the image by 50
brightened = pixels + 50 
# Output: [200, 250, 270, 290] -> 270 and 290 are illegal pixel values!

# Clip it to legally valid pixel ranges
safe_pixels = np.clip(brightened, 0, 255)

print(safe_pixels)
# Output: [200 250 255 255]

[200 250 255 255]


In [220]:
# Machine Learning (Gradient Clipping)
# When training deep neural networks, there is a common bug called "Exploding Gradients," where the mathematical updates to the model become so massively large that the model breaks and outputs NaN (Not a Number). Data scientists use np.clip to force the updates to stay within a safe range (like -1.0 to 1.0).

# Raw mathematical updates for the AI
gradients = np.array([-0.5, 0.2, -99.9, 0.8, 150.5]) 
# -99.9 and 150.5 are massive spikes that will destroy the model.

# Clip the gradients to keep the learning process stable
safe_gradients = np.clip(gradients, -1.0, 1.0)

print(safe_gradients)
# Output: [-0.5  0.2 -1.   0.8  1. ]

[-0.5  0.2 -1.   0.8  1. ]


In [221]:
# Sensor Data (Filtering Outlier Spikes)
# If you have a temperature sensor that normally reads between 60°F and 80°F, but occasionally glitches and outputs 999°F, clipping keeps your charts readable.

# Hourly temperature readings
temps = np.array([68, 70, 72, 999, 71, 69])

# Clip out the impossible hardware glitches (assume max logical temp is 120)
clean_temps = np.clip(temps, 0, 120)

print(clean_temps)
# Output: [ 68  70  72 120  71  69]

[ 68  70  72 120  71  69]


## 🏋️ Practice Tasks
### 🟢 Easy
1. Find the intersection of `[1, 2, 3]` and `[2, 3, 4]`.
2. Clip an array of temperatures `[-10, 15, 22, 35, 40]` between `0` and `30`.

### 🟡 Medium
3. Find elements in Array A that are NOT in Array B.
4. Generate 5 random numbers from a uniform distribution between 5 and 10.

### 🔴 Hard
5. Implement a custom "Clipped ReLU" (values below 0 become 0, values above 6 become 6) using `np.clip`.
6. Prove that `0.1 + 0.2 == 0.3` fails in NumPy, but `np.allclose` succeeds.

## 🎤 Interview Question
**Q:** Why do we need `np.allclose()` instead of `np.array_equal()`?
**A:** Computers represent floating-point numbers with finite precision. Operations like `np.sin(np.pi)` might return `1.22e-16` instead of exactly `0`. `np.allclose()` allows a small `rtol` (relative tolerance) and `atol` (absolute tolerance) to safely compare floats.


In [16]:
# ==========================================
# 💻 CONCEPT 5: SETS, CLIP, COMPARE
# ==========================================
A = np.array([1, 2, 3])
B = np.array([3, 4, 5])

# Easy
print("Intersection:", np.intersect1d(A, B))
temps = np.array([-10, 15, 22, 35, 40])
print("Clipped Temps:", np.clip(temps, 0, 30))

# Medium
print("A not in B (setdiff):", np.setdiff1d(A, B))
print("Uniform random:", np.random.uniform(5, 10, 5))

# Hard: Clipped ReLU & Float comparison
x = np.array([-2, -1, 0, 3, 5, 8, 10])
clipped_relu = np.clip(x, 0, 6)
print("\nClipped ReLU:", clipped_relu)

# Float precision proof
a = np.array([0.1 + 0.2])
b = np.array([0.3])
print(f"\n0.1 + 0.2 == 0.3? {a == b}")  # False!
print(f"np.allclose? {np.allclose(a, b)}")  # True!


Intersection: [3]
Clipped Temps: [ 0 15 22 30 30]
A not in B (setdiff): [1 2]
Uniform random: [6.97757585 8.03094357 7.98861783 8.96478047 8.27504669]

Clipped ReLU: [0 0 0 3 5 6 6]

0.1 + 0.2 == 0.3? [False]
np.allclose? True


# 🏁 NumPy Part 3 - Complete Recap & Mastery Checklist

## 📚 Topics Covered
| Category | Functions |
|----------|-----------|
| **Sorting/Searching** | `sort`, `unique`, `where`, `argmax`, `argmin`, `isin` |
| **Joining/Modifying** | `concatenate`, `append`, `delete`, `put`, `expand_dims`, `flip`, `swapaxes`, `tile`, `repeat` |
| **Math/Stats** | `cumsum`, `cumprod`, `percentile`, `histogram`, `corrcoef`, `count_nonzero` |
| **Sets/Clipping** | `union1d`, `intersect1d`, `setdiff1d`, `setxor1d`, `in1d`, `clip`, `allclose`, `array_equal` |
| **Random** | `np.random.uniform` |

## 🎯 Key Takeaways
✅ **`np.where`** is your best friend for vectorized `if-else` logic.
✅ **Never use `np.append` in a loop**; pre-allocate or use Python lists.
✅ **`np.clip`** is the fastest way to implement thresholding or bounded activations.
✅ **Always use `np.allclose`** when comparing floats.
✅ **Set operations** automatically flatten and sort your data.

## 🚀 Next Steps
You now know almost all the core NumPy functions required for Data Science! 
**Next up:** 
- Advanced Linear Algebra (`np.linalg`)
- Structured Arrays & Record Arrays
- Saving/Loading Data (`np.save`, `np.load`)

💡 **Pro Tip:** Try building a simple **K-Nearest Neighbors (KNN)** algorithm from scratch using only NumPy. You'll need `np.sqrt`, `np.argsort`, `np.bincount`, and broadcasting!

## 2. np.uniform

### Code Explanation

```python
import numpy as np

# ---------------------------------------------------------
# np.random.uniform: Generate random numbers from uniform distribution
# ---------------------------------------------------------
# Syntax: np.random.uniform(low, high, size)
# Generates numbers where every value between low and high is equally likely

# 10 random floats between 0 and 1
uniform_01 = np.random.uniform(0, 1, 10)
print("Uniform [0,1):", uniform_01)

# 5 random floats between -5 and 5
uniform_symmetric = np.random.uniform(-5, 5, 5)
print("Uniform [-5,5]:", uniform_symmetric)

# 2D array of shape (3, 4) between 10 and 20
uniform_2d = np.random.uniform(10, 20, (3, 4))
print("2D Uniform:\n", uniform_2d)
```

### The Core Concept

`np.random.uniform()` draws samples from a uniform distribution where all values in `[low, high)` have equal probability. This is the foundation of random initialization and sampling.

- **Half-open interval**: Includes `low` but excludes `high` (for floats)
- **Unlike `np.random.rand()`**: Allows custom ranges, not just [0, 1)
- **Deterministic with seed**: `np.random.seed(42)` makes results reproducible

### Practical Use Cases

**Use Case 1: Neural Network Weight Initialization**
```python
# Xavier/Glorot initialization for a layer with 100 inputs, 50 outputs
limit = np.sqrt(6 / (100 + 50))
weights = np.random.uniform(-limit, limit, (100, 50))
print("Weights range:", weights.min(), "to", weights.max())
```

**Use Case 2: Data Augmentation (Random Rotation)**
```python
# Add random rotation between -30° and 30° to images
rotation_angles = np.random.uniform(-30, 30, 1000)
print("Sample angles:", rotation_angles[:5])
```

**Use Case 3: Synthetic Dataset Generation**
```python
# Generate synthetic housing data
n_samples = 1000
sq_feet = np.random.uniform(500, 5000, n_samples)
bedrooms = np.random.uniform(1, 6, n_samples).astype(int)
price = 100 * sq_feet + 20000 * bedrooms + np.random.uniform(-10000, 10000, n_samples)
```

---

## 3. np.count_nonzero

### Code Explanation

```python
import numpy as np

# Sample array
arr = np.array([0, 1, 0, 0, 3, 0, 5, 0, 7])
print("Original:", arr)

# ---------------------------------------------------------
# np.count_nonzero: Count truthy/non-zero elements
# ---------------------------------------------------------
# Syntax: np.count_nonzero(array, axis=None)
# Counts elements that are not 0 and not False

# Count all non-zero elements
count = np.count_nonzero(arr)
print("Non-zero count:", count)  # 4

# Count along specific axis for 2D array
arr2D = np.array([[0, 1, 0],
                  [2, 0, 3],
                  [0, 4, 0]])

# Count non-zero per row (axis=1)
row_counts = np.count_nonzero(arr2D, axis=1)
print("Non-zero per row:", row_counts)  # [1, 2, 1]

# Count non-zero per column (axis=0)
col_counts = np.count_nonzero(arr2D, axis=0)
print("Non-zero per column:", col_counts)  # [1, 2, 1]

# Count with condition (elements greater than 2)
count_gt_2 = np.count_nonzero(arr > 2)
print("Count > 2:", count_gt_2)  # 2
```

### The Core Concept

`np.count_nonzero()` efficiently counts elements that evaluate to `True` in a boolean context (non-zero numbers, non-empty strings, etc.). It's a faster alternative to `len(arr[arr != 0])`.

- **Faster than sum()**: For boolean arrays, it's equivalent to `np.sum(arr != 0)` but often faster
- **Works with boolean masks**: `np.count_nonzero(array > threshold)` counts elements meeting a condition
- **Memory efficient**: Doesn't create intermediate arrays when used with conditions

### Practical Use Cases

**Use Case 1: Data Completeness Check**
```python
# Check how many missing values in a dataset
data = np.array([1.0, np.nan, 3.0, np.nan, 5.0])
missing_count = np.count_nonzero(np.isnan(data))
completeness = 1 - (missing_count / len(data))
print(f"Data completeness: {completeness:.1%}")  # 60%
```

**Use Case 2: Sparse Matrix Density**
```python
# Calculate sparsity of a matrix
sparse_matrix = np.array([[0, 0, 1],
                          [0, 0, 0],
                          [2, 0, 0]])
total_elements = sparse_matrix.size
non_zero = np.count_nonzero(sparse_matrix)
sparsity = 1 - (non_zero / total_elements)
print(f"Matrix sparsity: {sparsity:.1%}")  # 77.8%
```

**Use Case 3: Accuracy in Classification**
```python
# Calculate accuracy from predictions and labels
predictions = np.array([1, 0, 1, 1, 0, 1])
labels = np.array([1, 0, 0, 1, 0, 1])
correct = np.count_nonzero(predictions == labels)
accuracy = correct / len(labels)
print(f"Accuracy: {accuracy:.1%}")  # 83.3%
```

---

## 4. np.tile

### Code Explanation

```python
import numpy as np

# Sample array
arr = np.array([1, 2, 3])
print("Original:", arr)

# ---------------------------------------------------------
# np.tile: Repeat an array like floor tiles
# ---------------------------------------------------------
# Syntax: np.tile(array, repetitions)
# Constructs an array by repeating the input

# Repeat 1D array 3 times
tiled_1d = np.tile(arr, 3)
print("Tiled 1D (3x):", tiled_1d)  # [1 2 3 1 2 3 1 2 3]

# Repeat 2D pattern
pattern = np.array([[0, 1],
                    [1, 0]])
print("\nPattern:\n", pattern)

# Tile pattern: 2 times along rows, 3 times along columns
checkerboard = np.tile(pattern, (2, 3))
print("Checkered:\n", checkerboard)

# Simple scalar tile
tiled_scalar = np.tile(5, 4)
print("Tiled scalar:", tiled_scalar)  # [5 5 5 5]
```

### The Core Concept

`np.tile()` constructs a larger array by repeating the input array along specified dimensions, like laying tiles on a floor. Unlike `np.repeat()`, it repeats the **entire array** rather than individual elements.

- **Key difference from repeat**: `tile([1,2], 2)` → `[1,2,1,2]`, while `repeat([1,2], 2)` → `[1,1,2,2]`
- **Works with any dimension**: Can tile along multiple axes simultaneously
- **Common in pattern generation**: Checkerboards, grids, periodic structures

### Practical Use Cases

**Use Case 1: Checkerboard Pattern for Visualization**
```python
# Create 8x8 checkerboard
base = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(base, (4, 4))
print("Checkerboard shape:", checkerboard.shape)  # (8, 8)
```

**Use Case 2: Batch Processing Setup**
```python
# Create batch dimension by tiling
single_image = np.random.randn(32, 32, 3)  # One image
batch_size = 64
batch = np.tile(single_image[np.newaxis, ...], (batch_size, 1, 1, 1))
print("Batch shape:", batch.shape)  # (64, 32, 32, 3)
```

**Use Case 3: Expanding Features for Broadcasting**
```python
# Expand bias terms for matrix operations
biases = np.array([0.1, 0.2, 0.3])  # Shape (3,)
n_samples = 1000
expanded_biases = np.tile(biases, (n_samples, 1))
print("Expanded biases shape:", expanded_biases.shape)  # (1000, 3)
```

---

## 5. np.repeat

### Code Explanation

```python
import numpy as np

# Sample array
arr = np.array([1, 2, 3])
print("Original:", arr)

# ---------------------------------------------------------
# np.repeat: Repeat each element individually
# ---------------------------------------------------------
# Syntax: np.repeat(array, repeats, axis=None)

# Repeat each element 3 times
repeated = np.repeat(arr, 3)
print("Each element 3x:", repeated)  # [1 1 1 2 2 2 3 3 3]

# Different repeats per element
custom_repeat = np.repeat(arr, [1, 2, 3])
print("Custom repeats:", custom_repeat)  # [1 2 2 3 3 3]

# Repeat along axis for 2D array
arr2D = np.array([[1, 2],
                   [3, 4]])
print("\n2D Original:\n", arr2D)

# Repeat each row 2 times (axis=0)
row_repeat = np.repeat(arr2D, 2, axis=0)
print("Rows repeated:\n", row_repeat)

# Repeat each column 2 times (axis=1)
col_repeat = np.repeat(arr2D, 2, axis=1)
print("Columns repeated:\n", col_repeat)
```

### The Core Concept

`np.repeat()` duplicates each **element** of an array a specified number of times. Unlike `np.tile()`, it operates on individual elements, not the array as a whole.

- **Element-wise vs array-wise**: `repeat([1,2], 2)` → `[1,1,2,2]` vs `tile([1,2], 2)` → `[1,2,1,2]`
- **Flexible repeats**: Can specify different repetition counts for each element
- **Axis-specific**: Can repeat along rows or columns for multidimensional arrays

### Practical Use Cases

**Use Case 1: Upsampling Time Series Data**
```python
# Simple upsampling: repeat each time step 4 times
hourly_data = np.array([10, 15, 12, 18])
quarter_hourly = np.repeat(hourly_data, 4)
print("Upsampled:", quarter_hourly)  # [10 10 10 10 15 15 15 15 ...]
```

**Use Case 2: Creating Label Copies for Augmented Data**
```python
# Original labels and their augmentation factors
original_labels = np.array([0, 1, 2])  # 3 classes
augmentation_factors = np.array([5, 3, 4])  # Generate 5, 3, 4 copies

augmented_labels = np.repeat(original_labels, augmentation_factors)
print("Augmented labels:", augmented_labels)
print("Count per class:", np.bincount(augmented_labels))  # [5 3 4]
```

**Use Case 3: Expanding for Nearest-Neighbor Upsampling**
```python
# Upsample image by factor 2 using nearest neighbor
small_image = np.array([[1, 2],
                        [3, 4]])
# Repeat rows then columns
upsampled = np.repeat(np.repeat(small_image, 2, axis=0), 2, axis=1)
print("Upsampled 2x:\n", upsampled)
```

---

## 6. np.allclose

### Code Explanation

```python
import numpy as np

# ---------------------------------------------------------
# np.allclose: Check if arrays are element-wise equal within tolerance
# ---------------------------------------------------------
# Syntax: np.allclose(a, b, rtol=1e-05, atol=1e-08)
# Returns True if |a - b| <= atol + rtol * |b| for all elements

# Exact match
a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.0, 3.0])
print("Exact match:", np.allclose(a, b))  # True

# Floating point differences
x = np.array([0.1 + 0.2])  # 0.30000000000000004
y = np.array([0.3])         # 0.3
print("0.1+0.2 == 0.3:", x == y)           # False (floating point issue!)
print("allclose(0.1+0.2, 0.3):", np.allclose(x, y))  # True

# Custom tolerances
arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([1.01, 1.99, 3.02])
print("Default tolerance:", np.allclose(arr1, arr2))  # False
print("Relaxed tolerance:", np.allclose(arr1, arr2, atol=0.1))  # True

# NaN handling
arr_nan1 = np.array([1.0, np.nan, 3.0])
arr_nan2 = np.array([1.0, np.nan, 3.0])
print("NaN comparison:", np.allclose(arr_nan1, arr_nan2))  # False
print("NaN with equal_nan:", np.allclose(arr_nan1, arr_nan2, equal_nan=True))  # True
```

### The Core Concept

`np.allclose()` compares two arrays element-wise and returns `True` if all elements are equal within given tolerances. The comparison formula is: `|a - b| <= atol + rtol * |b|`

- **rtol (relative tolerance)**: Accounts for magnitude differences (default: 1e-5)
- **atol (absolute tolerance)**: Absolute minimum tolerance (default: 1e-8)
- **Essential for floating-point**: Never use `==` for float arrays

### Practical Use Cases

**Use Case 1: Verifying Numerical Algorithms**
```python
# Check if gradient computation is correct
def numerical_gradient(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)

def analytical_gradient(x):
    return 2 * x  # For f(x) = x^2

x = np.array([1.0, 2.0, 3.0])
num_grad = numerical_gradient(lambda x: x**2, x)
anal_grad = analytical_gradient(x)
print("Gradient check:", np.allclose(num_grad, anal_grad, rtol=1e-4))
```

**Use Case 2: Unit Testing Machine Learning Models**
```python
# Verify model output consistency
expected_output = np.array([0.7, 0.2, 0.1])
actual_output = np.array([0.7000001, 0.1999999, 0.1000002])
print("Output matches:", np.allclose(expected_output, actual_output))
```

**Use Case 3: Checking Matrix Inversion**
```python
# Verify A @ A_inv ≈ Identity
A = np.random.randn(4, 4)
A_inv = np.linalg.inv(A)
identity_check = A @ A_inv
print("Is inverse correct:", np.allclose(identity_check, np.eye(4)))
```

---

## 7. np.array_equal

### Code Explanation

```python
import numpy as np

# ---------------------------------------------------------
# np.array_equal: Check exact equality (shape AND values)
# ---------------------------------------------------------
# Syntax: np.array_equal(a, b)
# Returns True only if arrays have same shape and all elements equal

# Exact match
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
print("Same array:", np.array_equal(a, b))  # True

# Different shape
c = np.array([[1, 2, 3]])
print("Different shape:", np.array_equal(a, c))  # False

# Different values
d = np.array([1, 2, 4])
print("Different values:", np.array_equal(a, d))  # False

# Integer arrays - exact comparison
int_arr1 = np.array([1, 2, 3])
int_arr2 = np.array([1, 2, 3])
print("Integer equality:", np.array_equal(int_arr1, int_arr2))  # True

# Float comparison issue
float_arr1 = np.array([0.1 + 0.2])
float_arr2 = np.array([0.3])
print("Float equality:", np.array_equal(float_arr1, float_arr2))  # False!
print("Should use allclose for floats")

# NaN comparison
nan_arr1 = np.array([1, np.nan])
nan_arr2 = np.array([1, np.nan])
print("NaN equality:", np.array_equal(nan_arr1, nan_arr2))  # False
print("NaN equality (equal_nan):", np.array_equal(nan_arr1, nan_arr2, equal_nan=True))  # True
```

### The Core Concept

`np.array_equal()` returns `True` only if both arrays have **identical shapes** and **all corresponding elements are exactly equal** (bit-for-bit match for integers, exact float representation).

- **Strict comparison**: Even tiny floating-point differences matter
- **Shape-sensitive**: Different shapes always return `False`
- **NOT for floating-point**: Use `np.allclose()` for float comparisons
- **Fast for integers**: Perfect for comparing integer labels, indices, masks

### Practical Use Cases

**Use Case 1: Comparing Label Arrays**
```python
# Check if predictions exactly match ground truth
predictions = np.array([0, 1, 2, 1, 0])
ground_truth = np.array([0, 1, 2, 1, 0])
print("Perfect match:", np.array_equal(predictions, ground_truth))  # True
```

**Use Case 2: Verifying Array Slicing Operations**
```python
# Ensure view vs copy behavior
original = np.array([1, 2, 3, 4, 5])
sliced = original[1:4]
assert np.array_equal(sliced, np.array([2, 3, 4]))
```

**Use Case 3: Checking Index Alignment**
```python
# Verify train/test split indices don't overlap
all_indices = np.arange(1000)
train_idx = np.random.choice(all_indices, 800, replace=False)
test_idx = np.setdiff1d(all_indices, train_idx)

# Check that union of train and test gives all indices
reconstructed = np.sort(np.concatenate([train_idx, test_idx]))
print("Split correct:", np.array_equal(reconstructed, all_indices))  # True
```

---

## Comparison: allclose vs array_equal

```python
# When to use which?
import numpy as np

# Integer arrays: USE array_equal
labels1 = np.array([1, 2, 3])
labels2 = np.array([1, 2, 3])
print("Integer comparison:", np.array_equal(labels1, labels2))  # True

# Float arrays: USE allclose
values1 = np.array([0.1, 0.2, 0.3])
values2 = np.array([0.1, 0.2, 0.3])
print("Float with equal:", np.array_equal(values1, values2))  # Could be False!
print("Float with allclose:", np.allclose(values1, values2))  # True (safe)

# Shapes matter: allclose checks shapes implicitly
a = np.array([1.0, 2.0, 3.0])
b = np.array([[1.0, 2.0, 3.0]])
print("Different shapes - allclose:", np.allclose(a, b))  # False
print("Different shapes - equal:", np.array_equal(a, b))  # False
```

---

## Quick Decision Guide

| Function | Best For | Avoid For |
|----------|----------|-----------|
| **swapaxes** | Reshaping data for different libraries | Simple transposition (use `.T`) |
| **uniform** | Random initialization, sampling | Reproducible sequences without seed |
| **count_nonzero** | Sparsity, completeness, accuracy metrics | Counting specific values (use `np.sum(arr==val)`) |
| **tile** | Repeating entire arrays in patterns | Element-wise repetition (use `repeat`) |
| **repeat** | Upsampling, data augmentation | Array-wise repetition (use `tile`) |
| **allclose** | Floating-point comparisons, testing | Integer/boolean comparisons |
| **array_equal** | Integer/label comparison, exact matching | Float comparisons (use `allclose`) |