In [ ]:
from google.colab import drive

# Mount Google Drive (optional)
drive.mount('/content/drive')

# Clone your GitHub repository
!git clone https://github.com/beingAnujChaudhary/personalNotes.git

# Move into repository
%cd /content/personalNotes

# Move into Chapter 1 folder
%cd cd/notebooks/04_numpy

# 🚀 Concept 1: What is NumPy & Basic Array Creation

**NumPy** (Numerical Python) is the foundation of scientific computing in Python. At its core is the `ndarray` (n-dimensional array), which stores **homogeneous** data in contiguous memory blocks.


### ⚡ Why NumPy over Python Lists?
| Feature | Python List | NumPy Array |
|--------|-------------|-------------|
| **Memory** | Non-contiguous, stores object pointers | Contiguous, stores raw data |
| **Data Types** | Heterogeneous (mixed) | Homogeneous (single type) |
| **Performance** | Slower (Python-level loops) | C-optimized, vectorized operations |
| **Ecosystem** | General purpose | Foundation for Pandas, Scikit-Learn, PyTorch |

### 📊 Memory Diagram: List vs NumPy Array
```text
Python List: Scattered Memory (Slow)
[ ptr ] -> [ int obj ]
[ ptr ] -> [ float obj ]
[ ptr ] -> [ str obj ]

NumPy Array: Contiguous Memory (Fast)
[ 1 | 2 | 3 | 4 | 5 ] -> Single C-array block
```

💡 **Fun Fact:** NumPy was created by Travis Oliphant in 2005. The heavy lifting is done in C and Fortran, making it up to **100x faster** than native Python loops!


In [3]:
import numpy as np
import sys
import time

# ==========================================
# 💻 EXAMPLE: Speed & Memory Benchmark
# ==========================================

n = 10_000_000

# --- MEMORY COMPARISON ---
py_list = list(range(n))
# True memory of list = size of list object + size of all int objects
true_list_mem = sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list)

np_arr = np.arange(n, dtype=np.int32)
np_mem = np_arr.nbytes

print(f"📋 Python List Memory: {true_list_mem / 1e6:.2f} MB")
print(f"🔢 NumPy int32 Memory: {np_mem / 1e6:.2f} MB")
print(f"💾 Memory Saved: {true_list_mem / np_mem:.1f}x smaller!\n")

📋 Python List Memory: 360.00 MB
🔢 NumPy int32 Memory: 40.00 MB
💾 Memory Saved: 9.0x smaller!



In [4]:
# --- SPEED COMPARISON ---
# Python List
start = time.time()
py_sq = [x**2 for x in py_list[:1000000]] # Using 1M for speed
list_time = time.time() - start

# NumPy
start = time.time()
np_sq = np_arr[:1000000] ** 2
np_time = time.time() - start

print(f"⏱️ Python List Time: {list_time:.4f} s")
print(f"⏱️ NumPy Time:       {np_time:.6f} s")
print(f"⚡ Speedup:          {list_time/np_time:.1f}x faster!")

⏱️ Python List Time: 0.0981 s
⏱️ NumPy Time:       0.008066 s
⚡ Speedup:          12.2x faster!


In [5]:
# 1D Array (Vector)

arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array (Vector):", arr_1d)

1D Array (Vector): [1 2 3 4 5]


In [6]:
# 2D Array (Matrix)

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("2D Array (Matrix):\n", arr_2d)

2D Array (Matrix):
 [[1 2 3]
 [4 5 6]]


In [7]:
# 3D Array (Tensor)

arr_3d = np.array([[
    [1, 2],
    [3, 4],
    [5, 6]
]])
print("3D Array (Tensor):\n", arr_3d)

3D Array (Tensor):
 [[[1 2]
  [3 4]
  [5 6]]]


In [9]:
# Specifying Data Types (dtypes)

arrFloat32 = np.array([1, 2, 3], dtype=np.float32)
print("Float32 Array:", arrFloat32, "| Dtype", arrFloat32.dtype)
arrFloat64 = np.array([1, 2, 3], dtype=np.float64)
print("Float32 Array:", arrFloat64, "| Dtype", arrFloat64.dtype)

Float32 Array: [1. 2. 3.] | Dtype float32
Float32 Array: [1. 2. 3.] | Dtype float64


In [15]:
arrComplex = np.array([
    [4, 5, 6],
    [7, 8, 9]
], dtype=complex)

print("Complex Array:\n", arrComplex, "\nDtype", arrComplex.dtype)

Complex Array:
 [[4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]] 
Dtype complex128


In [22]:
arrBoolean = np.array([
    [0, 1],
    [5, 0]
], dtype=bool)

print("Boolean Array:\n", arrBoolean, "\nDtype", arrBoolean.dtype)

Boolean Array:
 [[False  True]
 [ True False]] 
Dtype bool


## 🏋️ Practice Tasks: Basic Creation
1. **Task 1:** Create a 1D array containing your age, birth month, and birth day.
2. **Task 2:** Create a 2D array (matrix) representing a 2x2 identity matrix manually using `np.array()`.
3. **Task 3:** Create a 1D array of the numbers `[10, 20, 30]` but force the data type to be `np.int8`. Print the array and its dtype.


<details>
<Summary>Click for solution</Summary>

```

# 💡 Solutions
# Task 1
my_dates = np.array([25, 10, 1995]) 
print("Task 1:", my_dates)

# Task 2
manual_eye = np.array([[1, 0], [0, 1]])
print("\nTask 2:\n", manual_eye)

# Task 3
arr_int8 = np.array([10, 20, 30], dtype=np.int8)
print("\nTask 3:", arr_int8, "| Dtype:", arr_int8.dtype)

```

</details>

**Q: Why are NumPy arrays faster and more memory-efficient than Python lists?**
> **A:** Python lists are arrays of pointers to scattered Python objects, requiring type-checking and boxing/unboxing on every operation. NumPy arrays store homogeneous data in **contiguous memory blocks** and use optimized, pre-compiled C code for vectorized operations, eliminating Python loop overhead.


# 🛠️ Concept 2: Specialized Array Creation

NumPy provides built-in functions to generate arrays without typing out every element.

### 📊 Visualizing `arange` vs `linspace`


In [63]:
# np.arange(start, stop, step)
# Works like Python's built-in range(). 
# Starts at 0, steps by 2, and stops BEFORE reaching 10.
# Output: [0, 2, 4, 6, 8]

print("arange:", np.arange(0, 10, 2))

arange: [0 2 4 6 8]


In [ ]:
# np.linspace(start, stop, num_points)
# Generates a specific NUMBER of evenly spaced points between two values.
# Starts at 0, ends exactly at 10 (inclusive by default), generating exactly 5 numbers.
# Output: [ 0.   2.5  5.   7.5 10. ]

print("linspace:", np.linspace(0, 10, 5))

linspace: [ 0.   2.5  5.   7.5 10. ]


### Pre-filled Arrays (Zeros and Ones)


In [65]:
# np.zeros(shape)
# Creates a 2D matrix with 2 rows and 3 columns filled entirely with 0.0 (floats).
# Often used to initialize empty placeholders for data.

print("\nZeros:\n", np.zeros((2, 3)))


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [67]:
# np.ones(shape)
# Creates a 2D matrix with 3 rows and 2 columns filled entirely with 1.0 (floats).

print("Ones:\n", np.ones((3, 2)))

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


### Random Array Generation

In [68]:
# np.random.rand(shape)
# Generates 3 random floating-point numbers.
# The numbers are uniformly distributed between 0 (inclusive) and 1 (exclusive).

print("\nRandom [0,1):", np.random.rand(3))


Random [0,1): [0.4398281  0.18241242 0.33268305]


In [69]:
# np.random.randint(low, high, size)
# Generates random integers starting from 1 up to (but NOT including) 100.
# size=(2, 2) structures these random integers into a 2x2 grid.

print("Random Ints:", np.random.randint(1, 100, size=(2, 2)))

Random Ints: [[12 64]
 [15 52]]


###  Special Matrices

In [71]:
# np.eye(N)
# Creates an NxN (here, 3x3) Identity Matrix.
# An identity matrix is a square matrix with 1s on the main diagonal and 0s elsewhere.

print("\nIdentity:\n", np.eye(3))


Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


💡 **Fun Fact:** The function `np.eye()` is pronounced "np-I" because it creates the Identity matrix (denoted as *I* in linear algebra)!


### Method Chaining (Creation + Modification)

In [72]:
# np.arange(1, 13).reshape(rows, columns)
# Step 1: np.arange(1, 13) creates a flat 1D array of 12 elements: [1, 2, 3... 12]
# Step 2: .reshape(3, 4) takes those 12 elements and molds them into a 2D grid with 3 rows and 4 columns.
# Note: The total number of elements must match (3 * 4 = 12).

print("\nReshaped arange:\n", np.arange(1, 13).reshape(3, 4))


Reshaped arange:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 🏋️ Practice Tasks: Specialized Creation
1. **Task 1:** Create an array of 5 evenly spaced numbers between 1 and 5 (inclusive).
2. **Task 2:** Create a 3x3 matrix filled entirely with the number `7`. *(Hint: use `ones` or `zeros` and multiply)*.
3. **Task 3:** Create a 4x4 matrix of random integers between 50 and 100.
4. **Task 4:** Create a 1D array of all even numbers from 10 to 30 using `arange`.
5.  Chain `np.arange()` and `.reshape()` to create a calendar grid for the month of February (28 days). The grid should have 4 rows (weeks) and 7 columns (days).
6.  Create a flat array of 24 numbers, and reshape it into a **3D tensor** with the shape `(2, 3, 4)` (e.g., 2 blocks, each containing 3 rows and 4 columns).

<details>
<Summary>Click for solution</Summary>

```
# 💡 Solutions
# Task 1
print("Task 1:", np.linspace(1, 5, 5))

# Task 2
print("\nTask 2:\n", np.ones((3, 3)) * 7)

# Task 3
print("\nTask 3:\n", np.random.randint(50, 101, size=(4, 4)))

# Task 4
print("\nTask 4:", np.arange(10, 31, 2))


```

</details>

## 🎤 Interview Question
**Q: What is the key difference between `np.arange()` and `np.linspace()`?**
> **A:** `np.arange()` generates values based on a **step size** and excludes the stop value (like Python's `range`). `np.linspace()` generates a specific **number of points** and includes the stop value by default. `linspace` is preferred for plotting axes to avoid floating-point precision issues.

# 📊 Concept 3: Array Attributes & Type Casting

Every `ndarray` has metadata describing its structure and memory footprint.

| Attribute | Description | Example |
|-----------|-------------|---------|
| `ndim` | Number of dimensions (axes) | 1, 2, 3... |
| `shape` | Tuple indicating size of each dimension  | `(3, 4)` |
| `size` | Total number of elements | `12` |
| `itemsize` | Memory size of **one** element in bytes | `8` for `float64` |
| `dtype` | Data type of elements | `int32`, `float64` |

### Examining Array Metadata    

In [81]:
# Create a 2D array (matrix) with 2 rows and 3 columns.
# We explicitly set the data type to 64-bit floats (float64).

arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [82]:
# arr.ndim: Number of dimensions (axes) of the array.
# Since it's a matrix consisting of rows and columns, it is 2-dimensional.

print("ndim:", arr.ndim)

ndim: 2


In [83]:
# arr.shape: A tuple representing the exact size of each dimension.
# Output is (2, 3) representing 2 rows and 3 columns.

print("shape:", arr.shape)

shape: (2, 3)


In [84]:
# arr.size: The total number of individual elements inside the array.
# 2 rows * 3 columns = 6 total elements.

print("size:", arr.size)

size: 6


In [85]:
# arr.itemsize: The memory size (in bytes) of a single element.
# Since we used float64, each number takes 64 bits. 
# Because 8 bits = 1 byte, 64 bits = 8 bytes per item.

print("itemsize:", arr.itemsize)

itemsize: 8


In [86]:
# arr.dtype: The uniform data type of the array's elements.

print("dtype:", arr.dtype)

dtype: float64


In [87]:
# arr.nbytes: Total bytes consumed by the array in your system's RAM.
# Formula: size (6) * itemsize (8) = 48 bytes.

print("Total Memory:", arr.nbytes, "bytes")

Total Memory: 48 bytes


#### 🔄 Concept 6: Type Casting (`astype`)
Sometimes, data is imported as highly precise `float64` numbers, but you only need standard integers. NumPy arrays have a fixed data type, meaning you cannot change them directly. Instead, you use `.astype()` to create a **new copy** of the array with the updated data type.

> 💡 **Pro Tip:** Downgrading from `float64` to `float32` or `int32` is a standard technique in Deep Learning to halve your RAM/VRAM usage with minimal loss of accuracy!

🔄 **Type Casting:** Use `arr.astype(new_dtype)` to change types. *Note: This always returns a **copy**, not a view!*


In [94]:
# Type Casting and Memory Reduction 

# arr.astype(new_dtype) creates a NEW array where every element 
# is converted from the original float64 to a 32-bit integer (int32).
# Note: Converting floats to integers truncates any decimal values.

arr_int = arr.astype(np.int32)

print("Casted to int32:\n", arr_int, "\n")

# A 32-bit integer takes up exactly 32 bits of memory.
# 32 bits / 8 = 4 bytes per item.
# By casting, we successfully reduced the memory footprint per element by 50%!

print("New itemsize:", arr_int.itemsize, "bytes")

Casted to int32:
 [[1 2 3]
 [4 5 6]] 

New itemsize: 4 bytes


In [101]:
sample = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

print(f"Dimensions (ndim): {sample.ndim}")
print(f"Shape: {sample.shape}")
print(f"Total Elements (size): {sample.size}")
print(f"Data Type (dtype): {sample.dtype}")
print(f"Total Memory (bytes): {sample.nbytes}")

# Changing dtype to save memory
int_version = sample.astype(np.int16)
print(f"\nCasted to int16. New Memory: {int_version.nbytes} bytes")

Dimensions (ndim): 2
Shape: (2, 3)
Total Elements (size): 6
Data Type (dtype): float64
Total Memory (bytes): 48

Casted to int16. New Memory: 12 bytes


## 🏋️ Practice Tasks: Attributes & Casting
1. **Task 1:** Create a 3D array of shape `(2, 3, 4)`. Without running code, predict its `ndim`, `shape`, and `size`.
2. **Task 2:** Create an array of 1000 `float64` elements. Calculate its total memory in Kilobytes (KB).
3. **Task 3:** Create an array `[1.9, 2.1, 3.8]` and cast it to `int32`. What happens to the decimal values?
4. **Task 4:** Create a `float64` array containing 50,000 simulated Kaggle dataset entries using `np.ones(50000)`. Check its `nbytes`. Convert it to `float32` using `.astype()` and check the memory savings.
5. **Task 5:** Create a boolean array representing whether 5 different hotel reservations are confirmed (`True` or `False`). Check its `dtype` and `ndim`.

<details>
<Summary>Click for solution</Summary>

```

# 💡 Solutions
# Task 1
arr_3d = np.zeros((2, 3, 4))
print("Task 1 -> ndim:", arr_3d.ndim, "| shape:", arr_3d.shape, "| size:", arr_3d.size)

# Task 2
arr_mem = np.zeros(1000, dtype=np.float64)
kb = arr_mem.nbytes / 1024
print("\nTask 2 -> Memory:", kb, "KB")

# Task 3
arr_dec = np.array([1.9, 2.1, 3.8])
print("\nTask 3 -> Casted:", arr_dec.astype(np.int32)) # Truncates decimals!

```

</details>

```

## 🎤 Interview Question
**Q: If I have a massive dataset in `float64` and I'm running out of RAM, how can I quickly halve the memory usage without losing the data structure?**
> **A:** Cast the array to `float32` using `arr.astype(np.float32)`. This reduces the `itemsize` from 8 bytes to 4 bytes, cutting the memory footprint (`nbytes`) exactly in half while maintaining the same `shape` and `size`.


# ⚡ Concept 4: Array Operations & Vectorization

NumPy supports **vectorized operations**, meaning you can perform mathematical operations (element-wise) on entire arrays without writing explicit Python `for` loops.

### 📊 Visualizing Operations

**Vector operations**: Element-wise math between arrays of the same shape.

```python
Scalar Op:  [1, 2, 3] + 10  =>  [11, 12, 13]
Vector Op:  
[1, 2, 3] * [2, 2, 2]  =>  [2, 4, 6]  (Element-wise!)
arr1 + arr2  # Element-wise addition
arr1 > arr2  # Element-wise comparison → returns a Boolean array
```

⚠️ **Crucial:** The `*` operator in NumPy is **element-wise multiplication**, NOT matrix multiplication!


In [95]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# Scalar Operations
print("Add 5:", a + 5)
print("Square:", a ** 2)
print("Greater than 15:", a > 15) # Returns boolean array

# Vector Operations
print("\nElement-wise Add:", a + b)
print("Element-wise Multiply:", a * b)

# Matrix Multiplication (Dot Product)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("\nElement-wise (*):\n", A * B)
print("Matrix Multiply (@):\n", A @ B) # or np.dot(A, B)


Add 5: [15 25 35]
Square: [100 400 900]
Greater than 15: [False  True  True]

Element-wise Add: [11 22 33]
Element-wise Multiply: [10 40 90]

Element-wise (*):
 [[ 5 12]
 [21 32]]
Matrix Multiply (@):
 [[19 22]
 [43 50]]


In [102]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Scalar Multiplication (* 2):", a * 2)
print("Vector Addition (a + b):", a + b)
print("Relational Comparison (a > 15):", a > 15)

# Masking: Filtering arrays based on conditions
mask = a > 15
print("Filtered Array:", a[mask])

Scalar Multiplication (* 2): [20 40 60]
Vector Addition (a + b): [11 22 33]
Relational Comparison (a > 15): [False  True  True]
Filtered Array: [20 30]


## 🏋️ Practice Tasks: Operations
1. **Task 1:** Create an array of numbers from 1 to 5. Add 10 to every element, then multiply the result by 2.
2. **Task 2:** Create two arrays `x = [1, 2, 3]` and `y = [4, 5, 6]`. Find the element-wise difference (`x - y`).
3. **Task 3:**  Create a boolean mask for an array `[10, 25, 30, 45]` where the value is greater than or equal to 25.
4. **Mini Challenge:** Calculate the dot product of `[1, 2, 3]` and `[4, 5, 6]` manually, then verify using `np.dot()`.
5. **Task 5:** You have a 1D array of local food delivery order totals in INR: `[250, 410, 180, 500]`. Apply a flat ₹40 delivery fee to the entire array without using a loop.
6. **Task 6:** Create an array of your daily protein intake in grams for a week. Create a boolean mask to filter and print only the days you hit your goal of >140g.

<details>
<Summary>Click for solution</Summary>

```

# 💡 Solutions
# Task 1
arr = np.arange(1, 6)
print("Task 1:", (arr + 10) * 2)

# Task 2
x, y = np.array([1, 2, 3]), np.array([4, 5, 6])
print("\nTask 2:", x - y)

# Task 3
arr2 = np.array([10, 25, 30, 45])
print("\nTask 3:", arr2 >= 25)

# Task 4 (Mini Challenge)
# Manual: (1*4) + (2*5) + (3*6) = 4 + 10 + 18 = 32
print("\nTask 4:", np.dot([1, 2, 3], [4, 5, 6]))

```

</details>

```


## 🎤 Interview Question
**Q: What is the difference between `A * B` and `A @ B` (or `np.dot(A,B)`) for 2D arrays?**
> **A:** `A * B` performs **Hadamard (element-wise) product**, multiplying corresponding elements. `A @ B` performs **Matrix Multiplication** (Dot Product), where rows of A are multiplied by columns of B.


# 📈 Concept 5: Array Functions & Aggregations

NumPy provides optimized math functions. Understanding the `axis` parameter is critical!

### 📊 The `axis` Paradigm
Understanding the `axis` parameter is critical for 2D arrays (matrices).
* `axis=0` → Operates vertically (Down columns, collapsing rows).
* `axis=1` → Operates horizontally (Across columns, collapsing columns per row).
```text
       axis=0 (Down / Columns)
         ↓   ↓   ↓
      [[ 1,  2,  3],  → axis=1 (Across / Rows)
       [ 4,  5,  6]]     → → →
```
**Rule of thumb:** 
1.`axis=0` collapses rows (operates vertically). 
2. `axis=1` collapses columns (operates horizontally).

**Key Functions:**
* `sum()`, `min()`, `max()`
* `mean()`, `median()`, `std()`

In [96]:
mat = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Aggregations
print("Total Sum:", mat.sum())
print("Col Max (axis=0):", mat.max(axis=0)) # [4, 5, 6]
print("Row Mean (axis=1):", mat.mean(axis=1)) # [2. 5.]

# Statistics
print("\nStd Dev:", mat.std())
print("Variance:", mat.var())

# Math Functions
angles = np.array([0, np.pi/2, np.pi])
print("\nSin:", np.sin(angles))

# Rounding
decimals = np.array([1.2, 2.6, -1.5])
print("\nFloor:", np.floor(decimals))
print("Ceil:", np.ceil(decimals))
print("Round:", np.round(decimals))


Total Sum: 21
Col Max (axis=0): [4 5 6]
Row Mean (axis=1): [2. 5.]

Std Dev: 1.707825127659933
Variance: 2.9166666666666665

Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]

Floor: [ 1.  2. -2.]
Ceil: [ 2.  3. -1.]
Round: [ 1.  3. -2.]


## 🏋️ Practice Tasks: Functions
1. **Task 1:** Create a 3x3 matrix of numbers 1 to 9. Find the sum of each **column**.
2. **Task 2:** Using the same matrix, find the maximum value of each **row**.
3. **Task 3:** Create an array `[1.1, 2.5, 3.9, -1.2]`. Apply `floor` and `ceil` to it.
4. **Mini Challenge:** Calculate the standard deviation of the array `[10, 12, 23, 23, 16, 23, 21, 16]`.
5. **Task 5:** Calculate the total monthly spending from a 1D array of 30 randomized daily expenses at local cafes using `np.random.randint(100, 500, 30)`.
6. **Task 6:** Given a 2D array representing daily technical support ticket resolution times (rows = days, columns = specific support agents), find the minimum resolution time for *each* agent using the correct `axis` parameter.

<details>
<Summary>Click for solution</Summary>

```

# 💡 Solutions
mat = np.arange(1, 10).reshape(3, 3)

# Task 1
print("Task 1 (Col Sum):", mat.sum(axis=0))

# Task 2
print("\nTask 2 (Row Max):", mat.max(axis=1))

# Task 3
arr = np.array([1.1, 2.5, 3.9, -1.2])
print("\nTask 3 Floor:", np.floor(arr))
print("Task 3 Ceil:", np.ceil(arr))

# Task 4
print("\nTask 4 Std Dev:", np.std([10, 12, 23, 23, 16, 23, 21, 16]))

```

</details>



## 🎤 Interview Question
**Q: If I have a 2D array of shape `(100, 5)` representing 100 students and 5 subjects, how do I find the average score for each subject?**
> **A:** You need to aggregate across the students (rows) to get one score per subject (column). Therefore, you use `arr.mean(axis=0)`. This collapses the 100 rows and returns an array of shape `(5,)`.


# 🎯 Concept 6: Indexing & Slicing

Extracting data using indices. 

**Crucial Rule:** Slicing returns a **VIEW**, not a copy! Modifying the slice modifies the original array.

* **Syntax:** `arr[start:stop:step]`
* **2D Syntax:** `arr[row_start:row_stop, col_start:col_stop]`
* ⚠️ **Crucial Note:** Slicing a NumPy array returns a **VIEW**, not a copy. Modifying a slice modifies the original array. Use `.copy()` if you want an isolated dataset.


In [97]:
grid = np.arange(1, 26).reshape(5, 5)
print("Original Grid:\n", grid)

# Basic Indexing
print("\nElement at row 1, col 2:", grid[1, 2]) # 8

# Slicing
print("\nFirst 2 rows, last 2 cols:\n", grid[:2, 3:])

# Boolean Masking
print("\nEven numbers:\n", grid[grid % 2 == 0])

# VIEW vs COPY demonstration
slice_view = grid[0, :]
slice_view[0] = 999
print("\nGrid after modifying slice:\n", grid) # 999 is in the grid!


Original Grid:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Element at row 1, col 2: 8

First 2 rows, last 2 cols:
 [[ 4  5]
 [ 9 10]]

Even numbers:
 [ 2  4  6  8 10 12 14 16 18 20 22 24]

Grid after modifying slice:
 [[999   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]


In [103]:
grid = np.arange(1, 13).reshape(3, 4)
print("Original Grid:\n", grid)

print("\nElement at Row 1, Col 2:", grid[1, 2])
print("\nFirst 2 Rows, Last 2 Cols:\n", grid[:2, 2:])

# View vs Copy demonstration
slice_view = grid[0, :]
slice_view[0] = 999
print("\nOriginal array mutated by view:\n", grid)

Original Grid:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at Row 1, Col 2: 7

First 2 Rows, Last 2 Cols:
 [[3 4]
 [7 8]]

Original array mutated by view:
 [[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


## 🏋️ Practice Tasks: Indexing
1. **Task 1:** Create a 4x4 array of numbers 1 to 16. Extract the center 2x2 matrix.
2. **Task 2:** Extract the entire 3rd column of the array.
3. **Task 3:** Extract all numbers greater than 10 from the array.
4. **Mini Challenge:** Reverse the rows of the 4x4 array (so the last row becomes the first).
5. **Task 5:** Create a 4x7 array (representing 4 weeks, 7 days) of daily flight delays using `np.random.randint(0, 60, (4, 7))`. Slice out the data specifically for the weekends (the last two columns).
6. **Task 6:** Create a slice of an array and safely alter it using `.copy()` to ensure the original array data remains completely unchanged.


<details>
<Summary>Click for solution</Summary>

```

# 💡 Solutions
mat = np.arange(1, 17).reshape(4, 4)

# Task 1
print("Task 1 (Center 2x2):\n", mat[1:3, 1:3])

# Task 2
print("\nTask 2 (3rd Col):", mat[:, 2])

# Task 3
print("\nTask 3 (>10):", mat[mat > 10])

# Task 4 (Mini Challenge)
print("\nTask 4 (Reverse Rows):\n", mat[::-1, :])

```

</details>


## 🎤 Interview Question
**Q: I sliced an array `b = a[2:5]` and changed a value in `b`. Why did `a` change, and how do I prevent this?**
> **A:** NumPy slicing returns a **view** to save memory, meaning `b` and `a` share the same underlying data buffer. To prevent this, explicitly create a copy using `b = a[2:5].copy()`.


# 🔄 Concept 7: Iteration, Reshaping & Flattening

While vectorization is preferred, sometimes you must iterate. For reshaping, remember that data is read in **C-contiguous (row-major)** order by default.

| Method | Description |
|--------|-------------|
| `.reshape(shape)` | Changes dimensions (e.g., 1D to 2D) |
| `.ravel()` | Flattens a multi-dimensional array to 1D |
| `np.vstack([a, b])` | Stacks arrays vertically (adds rows) |
| `np.hstack([a, b])` | Stacks arrays horizontally (adds columns) |

### 📊 Reshape & Transpose Visual
```text
Original (2x3)       Transpose (3x2)      Ravel (1x6)
[1, 2, 3]            [1, 4]               [1, 2, 3, 4, 5, 6]
[4, 5, 6]            [2, 5]
                     [3, 6]
```



In [ ]:
arr = np.arange(1, 7).reshape(2, 3)

# Iteration
print("Row by row:")
for row in arr:
    print(row)

print("\nElement by element (nditer):")
for item in np.nditer(arr):
    print(item, end=" ")

# Reshaping
print("\n\nReshape to 3x2:\n", arr.reshape(3, 2))
print("Transpose (.T):\n", arr.T)

# Ravel vs Flatten
ravel_view = arr.ravel()
flatten_copy = arr.flatten()

Row by row:
[1 2 3]
[4 5 6]

Element by element (nditer):
1 2 3 4 5 6 

Reshape to 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Transpose (.T):
 [[1 4]
 [2 5]
 [3 6]]


In [1]:
# Reshaping
arr = np.arange(12)
grid = arr.reshape(3, 4)

# Stacking
a = np.array([[1, 2]])
b = np.array([[3, 4]])

print("Vertical Stack:\n", np.vstack([a, b]))
print("\nHorizontal Stack:\n", np.hstack([a, b]))

NameError: name 'np' is not defined

## 🏋️ Practice Tasks: Iteration & Reshaping
1. **Task 1:** Create a 1D array of 12 elements. Reshape it into a 3D array of shape `(2, 2, 3)`.
2. **Task 2:** Take a 3x3 matrix and flatten it using `ravel()`. Change the first element of the flattened array to `0`. Did the original matrix change?
3. **Task 3:** Iterate through a 2D array and print only the elements that are divisible by 3.
4. **Mini Challenge:** Reshape a 1D array of 10 elements into a 2D array using the `-1` trick (let NumPy calculate the rows).
5. **Task 5:** Take a 1D array of 24 hourly temperature readings from New Delhi (`np.arange(24)`) and reshape it into a 4x6 grid.
6. **Task 6:** Horizontally stack two 1D arrays: one containing regional train booking counts (IRCTC) and the other containing airline booking counts to view the transit modes side-by-side.

<details>
<Summary>Click for solution</Summary>

```

# 💡 Solutions
# Task 1
arr_3d = np.arange(1, 13).reshape(2, 2, 3)
print("Task 1 Shape:", arr_3d.shape)

# Task 2
mat = np.arange(1, 10).reshape(3, 3)
flat = mat.ravel()
flat[0] = 0
print("\nTask 2 Original Mat:\n", mat) # Yes, it changed!

# Task 3
print("\nTask 3 (Div by 3):")
for item in np.nditer(mat):
    if item % 3 == 0:
        print(item, end=" ")

# Task 4 (Mini Challenge)
arr_10 = np.arange(10)
print("\n\nTask 4 (-1 trick):\n", arr_10.reshape(-1, 2)) # Becomes 5x2

```

</details>


## 🎤 Interview Question
**Q: What is the difference between `ravel()` and `flatten()`?**
> **A:** `ravel()` returns a **view** of the original array whenever possible (no memory copy, highly efficient). `flatten()` always returns a **deep copy** (allocates new memory). Use `ravel()` for performance, `flatten()` when you need to modify the 1D array without affecting the original.


# 📦 Concept 8: Stacking & Splitting

Combine or divide arrays along specific axes.

### 📊 Visual Guide
```text
vstack (Vertical):      hstack (Horizontal):
[A]                     [A | B]
[B]

vsplit (Rows):          hsplit (Cols):
[Top]                   [Left | Right]
[Bottom]
```


In [99]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stacking
print("vstack:\n", np.vstack((a, b)))
print("\nhstack:\n", np.hstack((a, b)))

# Splitting
big = np.arange(1, 13).reshape(4, 3)
print("\nOriginal:\n", big)

left, right = np.hsplit(big, 2) # Split into 2 equal column parts
print("\nhsplit Left:\n", left)

top, bottom = np.vsplit(big, 2) # Split into 2 equal row parts
print("\nvsplit Top:\n", top)


vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack:
 [[1 2 5 6]
 [3 4 7 8]]

Original:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


ValueError: array split does not result in an equal division

## 🏋️ Practice Tasks: Stacking & Splitting
1. **Task 1:** Create two 2x2 arrays of zeros and ones. Stack them vertically to create a 4x2 array.
2. **Task 2:** Create a 4x4 array of numbers 1 to 16. Split it horizontally into two 4x2 arrays.
3. **Task 3:** Create a 1D array `[1, 2, 3]` and `[4, 5, 6]`. Stack them to create a 2x3 matrix. *(Hint: `vstack` works on 1D arrays too!)*
4. **Mini Challenge:** You have a 3x4 array of features and a 3x1 array of labels. How do you combine them into a single 3x5 dataset?
5. **Task 5:** Take a 1D array of 24 hourly temperature readings from New Delhi (`np.arange(24)`) and reshape it into a 4x6 grid.
6. **Task 6:** Horizontally stack two 1D arrays: one containing regional train booking counts (IRCTC) and the other containing airline booking counts to view the transit modes side-by-side.
<details>
<Summary>Click for solution</Summary>

```

# 💡 Solutions
# Task 1
z = np.zeros((2, 2))
o = np.ones((2, 2))
print("Task 1:\n", np.vstack((z, o)))

# Task 2
mat = np.arange(1, 17).reshape(4, 4)
l, r = np.hsplit(mat, 2)
print("\nTask 2 Left:\n", l)

# Task 3
a, b = np.array([1, 2, 3]), np.array([4, 5, 6])
print("\nTask 3:\n", np.vstack((a, b)))

# Task 4 (Mini Challenge)
features = np.zeros((3, 4))
labels = np.ones((3, 1))
dataset = np.hstack((features, labels))
print("\nTask 4 Shape:", dataset.shape) # (3, 5)

```

</details>



## 🎤 Interview Question
**Q: What is the difference between `np.concatenate()`, `np.vstack()`, and `np.stack()`?**
> **A:** 
> - `np.concatenate()` joins a sequence of arrays along an **existing axis**.
> - `np.vstack()` and `np.hstack()` are convenience wrappers around `concatenate` specifically for vertical (axis=0) and horizontal (axis=1) stacking.
> - `np.stack()` joins arrays along a **new axis** (e.g., stacking three 2D arrays to create a 3D array).


# 🏁 Final Recap & Cheat Sheet

| Concept | Key Functions / Syntax |
| :--- | :--- |
| **Creation** | `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`, `np.random` |
| **Attributes** | `.ndim`, `.shape`, `.size`, `.dtype`, `.itemsize`, `.astype()` |
| **Math Ops** | `+`, `-`, `*` (element-wise), `@` / `np.dot()` (matrix mult) |
| **Aggregations** | `.sum()`, `.mean()`, `.max()`, `axis=0` (cols), `axis=1` (rows) |
| **Indexing** | `arr[r, c]`, `arr[start:stop]`, `arr[arr > 5]` (Boolean mask) |
| **Manipulation** | `.reshape()`, `.T`, `.ravel()`, `np.vstack()`, `np.hsplit()` |

🎉 **Congratulations!** You have mastered NumPy Part 1. You are now ready to tackle Pandas, Scikit-Learn, and Deep Learning frameworks!