In [ ]:
from google.colab import drive

# Mount Google Drive (optional)
drive.mount('/content/drive')

# Clone your GitHub repository
!git clone https://github.com/beingAnujChaudhary/personalNotes.git

# Move into repository
%cd /content/personalNotes

# Move into Chapter 1 folder
%cd notebooks/04_numpy

# 🚀 NumPy Part 3: Advanced Manipulation, Statistics & Set Operations

Welcome to Part 3! In this notebook, we transition from basic array creation to **powerful data manipulation, statistical analysis, and conditional logic**. These are the exact functions used daily in Pandas, Scikit-Learn, and Deep Learning frameworks.

## 🗺️ Roadmap
1. **Sorting & Searching** (`sort`, `unique`, `where`, `argmax`)
2. **Joining & Modifying** (`concatenate`, `append`, `delete`, `expand_dims`, `flip`)
3. **Cumulative Math & Stats** (`cumsum`, `percentile`, `histogram`, `corrcoef`)
4. **Set Operations & Clipping** (`union1d`, `intersect1d`, `clip`, `allclose`)

Let's dive in! 🏊‍♂️


In [11]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

print("🚀 NumPy Part 3 Initialized!")
print(f"NumPy Version: {np.__version__}")


🚀 NumPy Part 3 Initialized!
NumPy Version: 2.4.6


# 📊 Concept 1: Sorting & Finding Unique Elements

## 📝 Theory
- **`np.sort()`**: Returns a *sorted copy* of an array.
- **`np.unique()`**: Finds the unique elements in an array. It can also return the indices and counts of each unique element!

## 📊 Visual Diagram
```text
Original:  [3, 1, 2, 3, 1, 4]
   ↓ np.sort()
Sorted:    [1, 1, 2, 3, 3, 4]

   ↓ np.unique(return_counts=True)
Values:    [1, 2, 3, 4]
Counts:    [2, 1, 2, 1]
```

## ⚠️ Common Mistake
Using `arr.sort()` instead of `np.sort(arr)`. 
- `np.sort(arr)` returns a **copy** (original is unchanged).
- `arr.sort()` sorts **in-place** (modifies original, returns `None`).

## 🏋️ Practice Tasks
### 🟢 Easy
1. Sort a 1D array of random integers.
2. Find the unique values in an array.

### 🟡 Medium
3. Sort a 2D array **column-wise** (along `axis=0`).
4. Use `np.unique` to find how many times each number appears in an array.

### 🔴 Hard
5. Given a 2D array, flatten it, sort it, and find the top 3 most frequent elements.

## 🚀 Mini Challenge
Create an array of 100 random integers between 1 and 10. Find the unique values and their counts, then print the value that appears the most.

## 🎤 Interview Question
**Q:** What is the difference between `np.sort()` and `arr.sort()`?
**A:** `np.sort()` returns a sorted copy of the array, leaving the original unchanged. `arr.sort()` modifies the array *in-place* and returns `None`. In functional programming or data pipelines, `np.sort()` is generally preferred to avoid unintended side effects.

## 💡 Fun Fact
`np.unique()` is actually implemented using `np.sort()` under the hood! It sorts the array first, then looks for adjacent duplicates.


In [12]:
# ==========================================
# 💻 CONCEPT 1: SORTING & UNIQUE
# ==========================================
arr = np.array([3, 1, 2, 3, 1, 4])

# Easy
print("Sorted:", np.sort(arr))
print("Unique:", np.unique(arr))

# Medium
mat = np.array([[3, 1, 2], [1, 5, 2]])
print("\nSorted Column-wise (axis=0):\n", np.sort(mat, axis=0))

vals, counts = np.unique(arr, return_counts=True)
print(f"\nValue Counts:\n{dict(zip(vals, counts))}")

# Hard & Mini Challenge
np.random.seed(42)
rand_arr = np.random.randint(1, 11, 100)
vals, counts = np.unique(rand_arr, return_counts=True)
most_frequent = vals[np.argmax(counts)]
print(f"\nMini Challenge - Most frequent value: {most_frequent} (appeared {np.max(counts)} times)")


Sorted: [1 1 2 3 3 4]
Unique: [1 2 3 4]

Sorted Column-wise (axis=0):
 [[1 1 2]
 [3 5 2]]

Value Counts:
{np.int64(1): np.int64(2), np.int64(2): np.int64(1), np.int64(3): np.int64(2), np.int64(4): np.int64(1)}

Mini Challenge - Most frequent value: 8 (appeared 15 times)


# 🎯 Concept 2: Conditional Logic & Searching

## 📝 Theory
- **`np.where(condition, [x, y])`**: The vectorized version of `if-else`. If `x` and `y` are provided, it returns elements from `x` where condition is True, else `y`. If only `condition` is provided, it returns the **indices** where True.
- **`np.argmax()` / `np.argmin()`**: Returns the *indices* of the maximum/minimum values.
- **`np.isin(element, test_elements)`**: Checks if each element of an array is present in a test list.

## 📊 Visual Diagram
```text
Array:      [ 1, -2,  3, -4,  5]
Condition:  [ T,  F,  T,  F,  T]  (arr > 0)

np.where(cond, arr, 0):
Result:     [ 1,  0,  3,  0,  5]  (Replaces negatives with 0 -> ReLU!)

np.where(cond):
Result:     (array([0, 2, 4]),)   (Returns indices of True)
```

## ⚠️ Common Mistake
Forgetting that `np.where(condition)` returns a **tuple** of arrays (one for each dimension). To get a flat array of indices, use `np.where(condition)[0]` or `np.nonzero(condition)[0]`.

## 🏋️ Practice Tasks
### 🟢 Easy
1. Replace all even numbers in an array with `-1`.
2. Find the index of the maximum value in a 1D array.

### 🟡 Medium
3. Find the indices of all values greater than 5 in a 2D array.
4. Check which elements of `[1, 2, 3, 4, 5]` are present in `[2, 4, 6]`.

### 🔴 Hard
5. Implement the **ReLU** activation function using `np.where`.
6. Find the indices of the **top 3 largest** values in an array (Hint: combine `argsort` and slicing).

## 🎤 Interview Question
**Q:** How do you implement the ReLU function (`max(0, x)`) in NumPy?
**A:** You can use `np.maximum(0, arr)` (fastest), or `np.where(arr > 0, arr, 0)`, or `arr * (arr > 0)`.

## 🌍 Real World Use Case
`np.where` is the exact mechanism Pandas uses under the hood for `df['col'].apply(lambda x: ...)` and `np.where` in SQL! It's also used to create binary masks in image processing.


In [13]:
# ==========================================
# 💻 CONCEPT 2: WHERE, ARGMAX, ISIN
# ==========================================
arr = np.array([1, -2, 3, -4, 5])

# Easy
print("Replace even with -1:", np.where(arr % 2 == 0, -1, arr))
print("Index of max:", np.argmax(arr))

# Medium
mat = np.array([[1, 6, 3], [8, 2, 9]])
rows, cols = np.where(mat > 5)
print(f"\nIndices > 5 -> Rows: {rows}, Cols: {cols}")

print("isin check:", np.isin([1, 2, 3, 4, 5], [2, 4, 6]))

# Hard: ReLU & Top 3
print("\nReLU:", np.where(arr > 0, arr, 0))

data = np.array([10, 50, 30, 90, 40, 80, 20])
# argsort gives indices that would sort the array. We take the last 3 and reverse them.
top_3_indices = np.argsort(data)[-3:][::-1]
print(f"Top 3 indices: {top_3_indices} -> Values: {data[top_3_indices]}")


Replace even with -1: [ 1 -1  3 -1  5]
Index of max: 4

Indices > 5 -> Rows: [0 1 1], Cols: [1 0 2]
isin check: [False  True False  True False]

ReLU: [1 0 3 0 5]
Top 3 indices: [3 5 1] -> Values: [90 80 50]


# 🧩 Concept 3: Joining, Modifying & Reshaping

## 📝 Theory
- **`np.concatenate()`**: Joins a sequence of arrays along an existing axis.
- **`np.append()`**: Appends values to the end of an array. (Warning: flattens if axis is not specified!).
- **`np.delete()`**: Removes elements at specified indices.
- **`np.put()`**: Replaces specific elements *in-place* using flattened indices.
- **`np.expand_dims()`**: Adds a new axis (shape `(N,)` → `(1, N)`).
- **`np.flip()`**: Reverses the order of elements along an axis.
- **`np.tile()` / `np.repeat()`**: Constructs an array by repeating A the number of times given by reps.

## 📊 Visual Diagram
```text
expand_dims:
[1, 2, 3]  (shape: 3,)
   ↓ axis=0
[[1, 2, 3]] (shape: 1, 3)

flip:
[[1, 2],   ↓ flip(axis=1)   [[2, 1],
 [3, 4]]                      [4, 3]]
```

## ⚠️ Common Mistake
Using `np.append()` inside a `for` loop to build an array. 
**Why?** NumPy arrays are fixed in memory. `append` creates a brand new array and copies all data every single time, resulting in **O(N²)** time complexity! Always pre-allocate or use Python lists for loops, then convert to NumPy.

## 🏋️ Practice Tasks
### 🟢 Easy
1. Concatenate two 1D arrays.
2. Add a new axis to a 1D array to make it a column vector.

### 🟡 Medium
3. Delete the 2nd row from a 2D array.
4. Flip a 2D array horizontally (reverse columns).

### 🔴 Hard
5. Use `np.put` to replace the diagonal elements of a 3x3 matrix with `99`.
6. Explain the difference between `np.tile([1,2], 3)` and `np.repeat([1,2], 3)`.

## 🎤 Interview Question
**Q:** What is the difference between `np.tile` and `np.repeat`?
**A:** 
- `np.tile([1, 2], 3)` repeats the *whole array*: `[1, 2, 1, 2, 1, 2]`
- `np.repeat([1, 2], 3)` repeats *each element*: `[1, 1, 1, 2, 2, 2]`


In [14]:
# ==========================================
# 💻 CONCEPT 3: JOINING & MODIFYING
# ==========================================
a = np.array([1, 2])
b = np.array([3, 4])

# Easy
print("Concatenate:", np.concatenate([a, b]))
col_vec = np.expand_dims(a, axis=1)
print("Column vector shape:", col_vec.shape)

# Medium
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nDelete row 1:\n", np.delete(mat, 1, axis=0))
print("Flip horizontally:\n", np.flip(mat, axis=1))

# Hard: np.put
mat_3x3 = np.zeros((3, 3), dtype=int)
# Diagonal indices in flattened 3x3 are 0, 4, 8
np.put(mat_3x3, [0, 4, 8], [99, 99, 99])
print("\nMatrix with put diagonal:\n", mat_3x3)

# Tile vs Repeat
print("\nTile:", np.tile([1, 2], 3))
print("Repeat:", np.repeat([1, 2], 3))


Concatenate: [1 2 3 4]
Column vector shape: (2, 1)

Delete row 1:
 [[1 2 3]
 [7 8 9]]
Flip horizontally:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]

Matrix with put diagonal:
 [[99  0  0]
 [ 0 99  0]
 [ 0  0 99]]

Tile: [1 2 1 2 1 2]
Repeat: [1 1 1 2 2 2]


# 📈 Concept 4: Cumulative Math & Statistics

## 📝 Theory
- **`np.cumsum()` / `np.cumprod()`**: Returns the cumulative sum/product. Essential for calculating running totals or probability distributions.
- **`np.percentile()`**: Computes the nth percentile (e.g., median is 50th, quartiles are 25th/75th).
- **`np.histogram()`**: Computes the frequency distribution of data (doesn't plot it, just returns bins and counts!).
- **`np.corrcoef()`**: Returns the Pearson correlation matrix.
- **`np.count_nonzero()`**: Counts how many elements evaluate to True (or are non-zero).

## 📊 Visual Diagram
```text
Array:    [1, 2, 3, 4]
cumsum:   [1, 3, 6, 10]  (1, 1+2, 1+2+3, 1+2+3+4)

Histogram:
Data: [1, 1, 2, 3, 3, 3, 4]
Bins: [1, 2, 3, 4]
Counts: [2, 1, 3, 1]
```

## ⚠️ Common Mistake
Thinking `np.histogram()` draws a plot. It **only calculates the math** (returns `counts` and `bin_edges`). You must pass these to `plt.bar()` or `plt.hist()` to visualize it!

## 🏋️ Practice Tasks
### 🟢 Easy
1. Calculate the cumulative sum of `[1, 2, 3, 4, 5]`.
2. Find the 50th percentile (median) of an array.

### 🟡 Medium
3. Calculate the correlation coefficient between two arrays: `X = [1, 2, 3, 4, 5]` and `Y = [2, 4, 5, 4, 5]`.
4. Count how many `True` values exist in a boolean mask.

### 🔴 Hard
5. Normalize an array to a probability distribution using `cumsum`.
6. Compute the histogram of 1000 random normal numbers with 10 bins.

## 🎤 Interview Question
**Q:** What does `np.corrcoef(x, y)` return?
**A:** It returns a **2x2 symmetric matrix**. The diagonal contains `1.0` (correlation of x with x, and y with y). The off-diagonal elements contain the actual Pearson correlation coefficient between `x` and `y`.


In [15]:
# ==========================================
# 💻 CONCEPT 4: CUMULATIVE & STATS
# ==========================================
arr = np.array([1, 2, 3, 4, 5])

# Easy
print("Cumsum:", np.cumsum(arr))
print("Median (50th %ile):", np.percentile(arr, 50))

# Medium
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])
corr_matrix = np.corrcoef(x, y)
print(f"\nCorrelation Matrix:\n{corr_matrix}")
print(f"Correlation between X and Y: {corr_matrix[0, 1]:.3f}")

mask = np.array([True, False, True, True, False])
print("Count non-zero (True):", np.count_nonzero(mask))

# Hard: Histogram
data = np.random.randn(1000)
counts, bins = np.histogram(data, bins=10)
print(f"\nHistogram Counts: {counts}")
print(f"Histogram Bins: {np.round(bins, 2)}")


Cumsum: [ 1  3  6 10 15]
Median (50th %ile): 3.0

Correlation Matrix:
[[1.         0.77459667]
 [0.77459667 1.        ]]
Correlation between X and Y: 0.775
Count non-zero (True): 3

Histogram Counts: [  2  13  50 116 240 253 199  82  34  11]
Histogram Bins: [-3.57 -2.89 -2.2  -1.52 -0.84 -0.16  0.53  1.21  1.89  2.57  3.25]


# 🧮 Concept 5: Set Operations, Clipping & Comparisons

## 📝 Theory
- **Set Operations**: `np.union1d`, `np.intersect1d`, `np.setdiff1d`, `np.setxor1d`, `np.in1d`. (Note: These flatten arrays and return **unique, sorted** results).
- **`np.clip(arr, min, max)`**: Limits values to a specific range. Values below `min` become `min`, above `max` become `max`.
- **`np.allclose(a, b)`**: Checks if two arrays are element-wise equal within a tolerance (crucial for floats!).
- **`np.array_equal(a, b)`**: Checks if two arrays have the same shape and exact elements.
- **`np.random.uniform(low, high, size)`**: Draws samples from a uniform distribution.

## 📊 Visual Diagram
```text
A = [1, 2, 3]
B = [3, 4, 5]

intersect1d: [3]
union1d:     [1, 2, 3, 4, 5]
setdiff1d(A,B): [1, 2] (In A but not B)

Clipping:
Input:  [-5, 0, 5, 10]
Clip(0, 5): [0, 0, 5, 5]
```

## ⚠️ Common Mistake
Using `==` to compare floating-point NumPy arrays. Due to precision issues (e.g., `0.1 + 0.2 != 0.3`), `==` will return `False`. **Always use `np.allclose()` for floats.**

## 🏋️ Practice Tasks
### 🟢 Easy
1. Find the intersection of `[1, 2, 3]` and `[2, 3, 4]`.
2. Clip an array of temperatures `[-10, 15, 22, 35, 40]` between `0` and `30`.

### 🟡 Medium
3. Find elements in Array A that are NOT in Array B.
4. Generate 5 random numbers from a uniform distribution between 5 and 10.

### 🔴 Hard
5. Implement a custom "Clipped ReLU" (values below 0 become 0, values above 6 become 6) using `np.clip`.
6. Prove that `0.1 + 0.2 == 0.3` fails in NumPy, but `np.allclose` succeeds.

## 🎤 Interview Question
**Q:** Why do we need `np.allclose()` instead of `np.array_equal()`?
**A:** Computers represent floating-point numbers with finite precision. Operations like `np.sin(np.pi)` might return `1.22e-16` instead of exactly `0`. `np.allclose()` allows a small `rtol` (relative tolerance) and `atol` (absolute tolerance) to safely compare floats.


In [16]:
# ==========================================
# 💻 CONCEPT 5: SETS, CLIP, COMPARE
# ==========================================
A = np.array([1, 2, 3])
B = np.array([3, 4, 5])

# Easy
print("Intersection:", np.intersect1d(A, B))
temps = np.array([-10, 15, 22, 35, 40])
print("Clipped Temps:", np.clip(temps, 0, 30))

# Medium
print("A not in B (setdiff):", np.setdiff1d(A, B))
print("Uniform random:", np.random.uniform(5, 10, 5))

# Hard: Clipped ReLU & Float comparison
x = np.array([-2, -1, 0, 3, 5, 8, 10])
clipped_relu = np.clip(x, 0, 6)
print("\nClipped ReLU:", clipped_relu)

# Float precision proof
a = np.array([0.1 + 0.2])
b = np.array([0.3])
print(f"\n0.1 + 0.2 == 0.3? {a == b}")  # False!
print(f"np.allclose? {np.allclose(a, b)}")  # True!


Intersection: [3]
Clipped Temps: [ 0 15 22 30 30]
A not in B (setdiff): [1 2]
Uniform random: [6.97757585 8.03094357 7.98861783 8.96478047 8.27504669]

Clipped ReLU: [0 0 0 3 5 6 6]

0.1 + 0.2 == 0.3? [False]
np.allclose? True


# 🏁 NumPy Part 3 - Complete Recap & Mastery Checklist

## 📚 Topics Covered
| Category | Functions |
|----------|-----------|
| **Sorting/Searching** | `sort`, `unique`, `where`, `argmax`, `argmin`, `isin` |
| **Joining/Modifying** | `concatenate`, `append`, `delete`, `put`, `expand_dims`, `flip`, `swapaxes`, `tile`, `repeat` |
| **Math/Stats** | `cumsum`, `cumprod`, `percentile`, `histogram`, `corrcoef`, `count_nonzero` |
| **Sets/Clipping** | `union1d`, `intersect1d`, `setdiff1d`, `setxor1d`, `in1d`, `clip`, `allclose`, `array_equal` |
| **Random** | `np.random.uniform` |

## 🎯 Key Takeaways
✅ **`np.where`** is your best friend for vectorized `if-else` logic.
✅ **Never use `np.append` in a loop**; pre-allocate or use Python lists.
✅ **`np.clip`** is the fastest way to implement thresholding or bounded activations.
✅ **Always use `np.allclose`** when comparing floats.
✅ **Set operations** automatically flatten and sort your data.

## 🚀 Next Steps
You now know almost all the core NumPy functions required for Data Science! 
**Next up:** 
- Advanced Linear Algebra (`np.linalg`)
- Structured Arrays & Record Arrays
- Saving/Loading Data (`np.save`, `np.load`)

💡 **Pro Tip:** Try building a simple **K-Nearest Neighbors (KNN)** algorithm from scratch using only NumPy. You'll need `np.sqrt`, `np.argsort`, `np.bincount`, and broadcasting!