# Data PreProcessing

In [ ]:
# Importing the Libraries

# numpy is the core library for scientific computing in Python. It is heavily used for working with multi-dimensional arrays and complex mathematical operations.
# 'as np' creates a standard, widely-used shorthand alias so we don't have to type 'numpy' every time.
import numpy as np

# pandas is the go-to library for data manipulation and analysis. It allows us to load and work with structured, tabular data (called DataFrames).
# 'as pd' is the standard shorthand alias for pandas.
import pandas as pd

# matplotlib.pyplot is a module used to create static 2D charts, graphs, and visual plots (like scatter plots or histograms).
# 'as plt' is the standard shorthand alias for this specific plotting module.
import matplotlib.pyplot as plt

# seaborn is a statistical data visualization library built on top of matplotlib. It makes generating beautiful, complex charts with default themes much easier.
# 'as sns' is the standard shorthand alias for seaborn.
import seaborn as sns

# sklearn (Scikit-Learn) is the primary library used for machine learning in Python. It provides tools for algorithms, data preprocessing, and model evaluation.
# 'as sk' creates a shorthand alias for the library (though it is more common to import specific modules directly, e.g., 'from sklearn.model_selection import...').
import sklearn as sk

In [16]:
# pd.read_csv() is a pandas function used to read a Comma-Separated Values (CSV) file and load it into a structured two-dimensional table called a DataFrame.
# The 'r' placed immediately before the quote stands for "raw string". It tells Python to treat backslashes (\) as literal characters rather than escape characters, which is essential for reading Windows file paths correctly.
# The string inside the quotes is the absolute file path pointing to exactly where your data file is stored on your drive.
dataset = pd.read_csv(r'D:\Projects\personalNotes\assets\1_dataPreprocessing\Data.csv')

# .head() is a method that returns the first 5 rows of the dataset by default.
# Data scientists use this immediately after loading a dataset to get a quick visual preview of the data and verify that the columns and rows loaded as expected.
dataset.head()

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes


In [17]:
# .info() generates a concise, highly useful technical summary of the DataFrame.
# It displays the total number of entries (rows), the total number of columns, the name of each column, the count of non-null (non-missing) values in each column, and the data type of each column (e.g., int64, float64, object).
# print() outputs this summary report directly to your console or terminal.
print(dataset.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     str    
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     str    
dtypes: float64(2), str(2)
memory usage: 452.0 bytes
None


In [12]:
# X represents the independent variables (features) we use to make predictions.
# .iloc stands for "integer location" and is used to select rows and columns by their numerical index.
# [:, :-1] is split into two parts by the comma:
#    1st part ':' means "give me ALL the rows".
#    2nd part ':-1' means "give me all the columns EXCEPT the very last one".
# .values extracts just the raw data as a NumPy array (stripping away the pandas row/column labels), which is required by machine learning libraries.
X = dataset.iloc[:, :-1].values 

# y represents the dependent variable (the target/label we are trying to predict).
# [:, -1] is also split into two parts:
#    1st part ':' means "give me ALL the rows".
#    2nd part '-1' means "give me ONLY the very last column".
# .values again converts this into a NumPy array.
y = dataset.iloc[:, -1].values

In [20]:
# print(X) displays the feature matrix (independent variables) we extracted from the dataset.
# Looking at the output, we can see a 2D array consisting of 3 columns: Country (categorical data), Age (numerical data), and Salary (numerical data).
# Note the presence of 'nan' (Not a Number) values in the Age and Salary columns. This indicates missing data that will need to be handled during the preprocessing phase.
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [21]:
# print(y) displays the dependent variable vector (the target).
# The output shows a 1D array of strings containing categorical labels ('No' and 'Yes'), representing the specific outcomes we want our machine learning model to predict.
print(y)

<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str


## Taking Care of Missing Values

In [23]:
# from sklearn.impute import SimpleImputer imports a specific class (SimpleImputer) from Scikit-Learn's imputation module.
# This class is specifically designed to handle and replace missing data in a dataset.
from sklearn.impute import SimpleImputer

# Here we are creating an 'instance' (or object) of the SimpleImputer class and naming it 'imputer'.
# missing_values=np.nan tells the imputer to look specifically for empty values represented by NumPy's 'nan' (Not a Number).
# strategy='mean' tells the imputer how to fill those empty spots: by calculating the mathematical average (mean) of the column and inserting it.
imputer = SimpleImputer(
    missing_values=np.nan, 
    strategy='mean'
)

# .fit() is a crucial machine learning method. It connects the imputer to our specific data to do the necessary math.
# X[:, 1:3] targets all rows (the ':' part), but only columns at index 1 and index 2. Remember, in Python slicing, the upper bound '3' is excluded.
# During this 'fit' step, the imputer looks at the Age (index 1) and Salary (index 2) columns and calculates their respective averages. It does not alter the data yet.
imputer.fit(X[:, 1:3])

# .transform() takes the averages calculated in the 'fit' step and actually applies them to the data, replacing all the 'nan' values with those averages.
# Note: By itself, this line just outputs the newly filled columns. To permanently update your 'X' matrix, you would usually assign it back, like this: X[:, 1:3] = imputer.transform(X[:, 1:3])
imputer.transform(X[:, 1:3])

# print(X) outputs the matrix to the console so we can verify the data.
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding Categorical Data

---

## **Encoding Categorical Data (The Overview)**

**The Problem:** Machine learning models are entirely based on mathematical equations. They only understand numbers. If you feed a model a dataset containing text or categories (like "France", "Spain", "Red", or "Yes"), it will throw an error because it cannot multiply or subtract words.

**The Solution:** Encoding is the process of translating those text-based categories into numbers so the model can process them, while preserving the underlying information.

There are two main types of categorical data, and how we encode them depends on the type:

* **Nominal Data:** Categories with *no inherent order* (e.g., Countries, Colors).
* **Ordinal Data:** Categories with a *strict order* (e.g., Clothing sizes: Small, Medium, Large).

---

## **What is One-Hot Encoding?**

**One-Hot Encoding** is the standard technique used to convert **Nominal** (unordered) categorical data into numbers.

**How it works:**
Instead of assigning a single number to each category (e.g., France = 0, Spain = 1, Germany = 2), it creates a brand-new binary column (consisting of 0s and 1s) for *every single unique category*.

* `1` means the category is "Hot" (True / Present).
* `0` means the category is "Cold" (False / Absent).

**Visual Example:**
If your original dataset has a single `Country` column:

| Original `Country` | `Is_France` | `Is_Spain` | `Is_Germany` |
| --- | --- | --- | --- |
| France | **1** | 0 | 0 |
| Spain | 0 | **1** | 0 |
| Germany | 0 | 0 | **1** |

**Why do we do this? (The "Relational" Problem)**
If we just assigned numbers (France=0, Spain=1, Germany=2), the mathematical model would look at the numbers and assume a false hierarchy. It would think that Germany (2) is somehow "greater than" Spain (1), or that France + Spain = Germany. One-Hot Encoding prevents this by putting every category on an equal, independent playing field.

---

## **Encoding the Independent Variable (Features / X)**

Independent variables (your `X` matrix) are the features the model uses to make predictions.

* **Technique Used:** `OneHotEncoder` (wrapped in a `ColumnTransformer`).
* **Why?** Because you usually have multiple independent variables, and your categorical features (like Country, User Browser, or Car Brand) rarely have a mathematical ranking. You must use One-Hot Encoding to prevent the model from giving unfair mathematical weight to a specific category.
* **Code Implementation:**
```python
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# We use ColumnTransformer to apply the OneHotEncoder ONLY to the specific categorical column (e.g., index 0)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

```



---

## **Encoding the Dependent Variable (Target / y)**

The dependent variable (your `y` vector) is the specific outcome you are trying to predict (e.g., "Did they buy the product? Yes or No").

* **Technique Used:** `LabelEncoder`.
* **Why?** The target variable does not require One-Hot Encoding. The machine learning model is not using this column to perform complex mathematical calculations; it is simply trying to map the input features to these final outcome buckets. Therefore, converting "No" to `0` and "Yes" to `1` is perfectly safe and expected by the algorithms.
* **Code Implementation:**
```python
from sklearn.preprocessing import LabelEncoder
# We simply transform the 1D target vector into integers
le = LabelEncoder()
y = le.fit_transform(y)

```

### One Hot Encoding

In [ ]:
# from sklearn.compose import ColumnTransformer imports a tool that allows us to apply different transformations to different columns in our dataset simultaneously.
from sklearn.compose import ColumnTransformer

# from sklearn.preprocessing import OneHotEncoder imports a tool used to convert categorical data (like text) into numbers. 
# It does this by creating a new binary (0 or 1) column for each unique category, preventing the machine learning model from assuming a false numerical ranking (e.g., that Country 2 is "greater" than Country 1).
from sklearn.preprocessing import OneHotEncoder

# Here we create an instance of the ColumnTransformer and configure its rules.
ct = ColumnTransformer(
    # 'transformers' takes a list of tuples. Each tuple specifies one transformation we want to apply.
    transformers=[
        (
            'encoder',        # A name we give to this specific transformation step (can be anything).
            OneHotEncoder(),  # The actual tool/class we are using to perform the transformation.
            [0]               # The index of the column(s) we want to apply this to. Index 0 is our 'Country' column.
        )
    ],
    # 'remainder' tells the ColumnTransformer what to do with the columns we DID NOT specify in the transformers list (in this case, Age and Salary).
    # 'passthrough' means "leave them exactly as they are and keep them in the dataset." If we didn't include this, those columns would be deleted!
    remainder='passthrough'
)

# .fit_transform(X) does two things at once: it learns the unique categories in column 0 (France, Spain, Germany) and immediately transforms them into binary columns.
# np.array() wraps the output to ensure the final result is strictly a NumPy array. This is an absolutely crucial step, as some machine learning models will throw an error if they don't receive the data in this exact format.
# Finally, we overwrite our original 'X' matrix with this newly transformed matrix.
X = np.array(ct.fit_transform(X))

In [31]:
# print(X) displays the updated matrix.
# If you look at the output, the single 'Country' text column at the beginning has been replaced by three separate columns of 0s and 1s representing France, Spain, and Germany. The Age and Salary columns remain untouched at the end.
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 nan]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
# from sklearn.preprocessing import LabelEncoder imports a tool specifically designed to convert categorical target labels (text) into numerical values.
# Unlike OneHotEncoder (which creates multiple columns and is strictly used for independent variables/features), LabelEncoder simply translates a single column into numbers (e.g., 0, 1, 2). It is highly recommended to only use LabelEncoder for your dependent variable (the target).
from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder() creates an instance (an object) of the LabelEncoder tool so we can use its functions.
le = LabelEncoder()

# .fit_transform(y) performs two steps simultaneously:
# 1. 'fit' analyzes the 'y' vector to find all unique text categories (in our case, 'No' and 'Yes') and assigns each a specific integer (e.g., 0 for 'No', 1 for 'Yes').
# 2. 'transform' actually applies those assigned numbers to the data, replacing the text.
# We then save this newly transformed, purely numerical array back into our 'y' variable, overwriting the old text version.
y = le.fit_transform(y)

# print(y) outputs our updated target vector to the console so we can verify the transformation.
# Instead of seeing an array of text like ['No', 'Yes', 'No', ...], we will now see an array of numbers like [0, 1, 0, ...], which is exactly the format a machine learning model requires to make mathematical predictions.
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the Dataset into Training set and Test set

In [37]:
# from sklearn.model_selection import train_test_split imports a highly utilized function from scikit-learn.
# Its entire purpose is to randomly shuffle your dataset and split it into two distinct sets: a Training set (to teach the model) and a Test set (to evaluate the model's performance on unseen data).
from sklearn.model_selection import train_test_split

# Here, the function executes the split and returns exactly four separate arrays. We use Python's "unpacking" feature to assign them to four variables at once.
# The order of these four variables (X_train, X_test, y_train, y_test) is absolutely mandatory, as that is the exact order the function spits them out.
X_train, X_test, y_train, y_test = train_test_split(
    # The first two arguments are the arrays you want to split: your features matrix (X) and your target vector (y).
    X,
    y,
    
    # test_size=0.2 dictates the exact ratio of the split. 
    # Here, 20% of the data will be reserved for testing, while the remaining 80% will be used for training the model. (An 80/20 split is widely considered the industry standard).
    test_size=0.2,  
    
    # random_state=1 controls the random number generator used to shuffle the data before splitting.
    # Setting a random seed (like 1, 42, or any integer) ensures that the split is completely reproducible. Every time you run this exact code, the data will be shuffled and split in the exact same way, which is crucial for debugging or following along with tutorials!
    random_state=1   
)

## Feature Scaling


### **What is Feature Scaling?**

Feature scaling is a critical data preprocessing step used to standardize the range of independent variables (features) in your dataset. Because machine learning models often calculate the mathematical distance between data points, having features on wildly different scales (e.g., Age ranging from 18-80 vs. Salary ranging from $50,000-$150,000) will cause the model to unfairly weigh the larger numbers.

The image you provided highlights the two most common techniques to fix this:

**1. Normalisation (Min-Max Scaling)**


$$x_{\text{norm}} = \frac{x - \text{min}(x)}{\text{max}(x) - \text{min}(x)}$$

* **What it does:** It squishes all your data points into a fixed, tight range—almost always between **0 and 1**.
* **How it works:** It subtracts the minimum value in the column from the data point, and divides by the range of the column.
* **When to use it:** Normalization is great when you know your data doesn't have extreme outliers, or when your model strictly requires data within a bounded scale (like certain Neural Networks).

**2. Standardisation (Z-Score Scaling)**


$$x_{\text{stand}} = \frac{x - \text{mean}(x)}{\text{standard deviation}(x)}$$

* **What it does:** It centers your data around a **mean of 0** with a **standard deviation of 1**. The resulting numbers can be positive or negative, and they are not restricted to a specific bounding box like 0 to 1.
* **How it works:** It shifts the data by subtracting the average, and scales it by dividing by the standard deviation.
* **When to use it:** Standardization is much more robust to outliers than Normalization. It is generally the go-to default for most machine learning algorithms (like Support Vector Machines, K-Means Clustering, and Principal Component Analysis).

---

This is a classic dilemma when building machine learning pipelines. While both techniques aim to put your features on an equal playing field, they do so in entirely different ways.

### Should we go for Standardization or Normalization?

The short answer is: **Standardization is generally your safest default choice**, but the exact decision depends heavily on the specific algorithm you are using and the shape of your data.

Here is a breakdown to help you make the right choice for your model.

### **Normalization (Min-Max Scaling)**

Normalization binds your data to a strict, fixed range—almost always exactly between 0 and 1.

* **When to use it:** * When your data does not follow a normal distribution (a bell curve).
* When you are dealing with features that have hard, natural boundaries (e.g., image processing where pixel intensities strictly range from 0 to 255).
* When the specific algorithm you are using strictly requires bounded data. Artificial Neural Networks (like those built in TensorFlow or PyTorch) often converge faster when inputs are normalized between 0 and 1.


* **The major flaw:** Normalization is completely crushed by outliers. If 99% of your data is between $50,000 and $100,000, but you have one outlier of $10,000,000, Normalization will squish your $50k-$100k data into a tiny, indistinguishable sliver (like 0.01 to 0.02) just to accommodate that single massive outlier at 1.0.

### **Standardization (Z-Score Scaling)**

Standardization does not restrict your data to a specific bounding box. Instead, it centers the data around a mean of 0 and a standard deviation of 1.

* **When to use it:**
* **As your default.** If you are unsure, start here.
* When your data roughly follows a normal distribution (Gaussian).
* When you are using algorithms that assume your data is centered around zero and variance matters. This includes Principal Component Analysis (PCA), Support Vector Machines (SVMs), Logistic Regression, and K-Means Clustering.


* **The major advantage:** It is highly resilient to outliers. Because it relies on the mean and standard deviation rather than the absolute minimum and maximum values, a massive outlier will not compress the rest of your useful data into a tiny fraction of the scale.

---

### **The Verdict**

| Feature | Normalization | Standardization |
| --- | --- | --- |
| **Output Range** | Strictly bounded (usually [0, 1]) | Unbounded (centered at 0) |
| **Impact of Outliers** | Highly sensitive (outliers ruin the scale) | Robust (handles outliers well) |
| **Best Used For** | Neural Networks, Image Processing, K-Nearest Neighbors | PCA, SVMs, Linear/Logistic Regression, K-Means |
| **Underlying Distribution** | Best when distribution is unknown/non-Gaussian | Best when data is Gaussian (bell curve) |

**Practical Workflow:** In professional model development, it is very common to default to **Standardization** first. If the model is underperforming—or if you are moving into deep learning where inputs need to be strictly bounded—you can swap out the scaler for Normalization and compare the validation scores.



### Do we have to apply feature scaling  before or after the splitting the dataset?

As we touched on earlier, you must **always apply feature scaling AFTER splitting your dataset** into training and testing sets.

If we look at the formulas in your image, the reason becomes very obvious:
Notice how both equations require calculating the **$\text{mean}(x)$**, the **$\text{min}(x)$**, or the **$\text{max}(x)$**.

If you scale *before* splitting, those calculations will include the data from your test set. Your training data will be transformed using the average and maximum values of the entire dataset. This causes **Data Leakage**, meaning your model gets a "sneak peek" at the test set's distribution before it ever tries to predict it.

To do it correctly:

1. Split the data.
2. Find the $\text{mean}$/$\text{max}$/$\text{min}$ using **only** the training set.
3. Apply those specific training-set calculations to both the training set and the test set.



In [38]:
# from sklearn.preprocessing import StandardScaler imports the specific tool we need to perform Standardization (Z-Score scaling).
# As discussed earlier, this will center our data around a mean of 0 and a standard deviation of 1, making it highly robust to outliers.
from sklearn.preprocessing import StandardScaler

# sc = StandardScaler() creates an instance (an object) of the scaler so we can use its mathematical functions.
sc = StandardScaler() 

# This line does three critical things at once for our TRAINING set:
# 1. The slice [:, 3:] selects ALL rows, but ONLY the columns from index 3 to the end. This intentionally skips our dummy variables at index 0, 1, and 2, ensuring they remain untouched 0s and 1s.
# 2. .fit_transform() calculates the mean and standard deviation exclusively from this specific slice of the training data (the 'fit' part), and immediately scales the numbers (the 'transform' part).
# 3. Finally, it takes these freshly scaled numbers and permanently overwrites the original columns in X_train.
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

# This line handles our TEST set, and it is where we prevent Data Leakage:
# 1. We again use the slice [:, 3:] to skip the dummy variables and target only the continuous features.
# 2. We strictly use .transform() here. The scaler remembers the exact mean and standard deviation it calculated from the training set in the line above, and applies those same mathematical rules to the test set. It does NOT calculate a new average for the test set!
# 3. The scaled test numbers are then saved back into the X_test matrix.
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [39]:
print(X_train)

[[1.0 0.0 0.0 1.2909944487358056 nan -1.0182239953527132]
 [1.0 0.0 1.0 -0.7745966692414834 -0.038910211282047996 nan]
 [0.0 1.0 0.0 -0.7745966692414834 0.5058327466666259 0.583476671494251]
 [1.0 0.0 0.0 1.2909944487358056 -0.3112816902563849 -0.2974586952715793]
 [1.0 0.0 0.0 1.2909944487358056 -1.809324824615238 -1.3385641287221062]
 [0.0 1.0 0.0 -0.7745966692414834 1.0505757046152997 1.1440719048906884]
 [1.0 0.0 1.0 -0.7745966692414834 1.3229471835896367 1.4644120382600814]
 [0.0 1.0 0.0 -0.7745966692414834 -0.7198389087178904 -0.537713795298624]]


In [40]:
print(X_test)

[[1.0 0.0 1.0 -0.7745966692414834 -1.4007676061537326 -0.8580539286680168]
 [0.0 1.0 0.0 -0.7745966692414834 -0.4474674297435534 0.18305150478250995]]


### Do we have to apply feature scaling, either Standardization or Normalization, to the dummy variables in the matrix of features?



The short answer is: **No, you should not apply feature scaling to dummy variables.**

This is a very common point of debate when learning data preprocessing, but standard practice dictates leaving your dummy variables exactly as they are. Here is exactly why:

### **1. They are already on a tiny scale**

The entire goal of feature scaling is to prevent features with massive numbers (like a $80,000 salary) from mathematically dominating features with small numbers (like a 30-year-old age).

Dummy variables, created by One-Hot Encoding, consist exclusively of **0s and 1s**. Because they are already bounded within this tiny range, they will never overpower your other features. Once you scale your continuous variables (like Age and Salary) down to similar ranges (e.g., between -2 and +2), everything will naturally be on an equal playing field.

### **2. You destroy the interpretation of the data**

A dummy variable has a specific, logical meaning:

* `1` means "Yes, this observation belongs to this category" (e.g., Yes, this person is from France).
* `0` means "No, they do not."

If you apply Standardization to a column of 0s and 1s, those numbers will be transformed into bizarre decimals like `-1.24` and `0.89`. While the machine learning model can technically still process these decimals, you completely lose the real-world meaning of the feature without actually improving the model's mathematical performance.

---


### What are the **`fit`** and **`transform`**?

In machine learning (specifically when using libraries like Scikit-Learn), **`fit`** and **`transform`** are the two fundamental steps required to process your data.

To understand them, it helps to think of a tailor making a custom suit:

* **`fit`** is taking the measurements.
* **`transform`** is actually cutting and sewing the fabric based on those measurements.

Here is the technical breakdown of exactly what each method does:

### **1. `fit()` = "Learn the Math"**

When you call `.fit()`, the algorithm looks at your dataset and calculates the specific internal parameters it needs to do its job. **It does not change your data at this stage.** It is simply learning about it.

* **For a `StandardScaler`:** It calculates the *mean* and *standard deviation* of your columns.
* **For a `SimpleImputer`:** It calculates the *average* of a column so it knows what to put in the blank spaces later.
* **For a `LabelEncoder`:** It looks at your text column and learns all the *unique categories* (e.g., finding out that the column contains "France," "Spain," and "Germany").

### **2. `transform()` = "Apply the Math"**

When you call `.transform()`, the algorithm takes the parameters it just learned in the `fit()` step and actually applies them to modify your dataset.

* **For a `StandardScaler`:** It takes the mean and standard deviation it memorized and uses them to scale your numbers down.
* **For a `SimpleImputer`:** It takes the average it memorized and permanently writes it into the missing `nan` slots.
* **For a `LabelEncoder`:** It swaps out the text for the numbers it assigned (e.g., replacing "France" with 0).

### **3. `fit_transform()` = "Do Both at Once"**

Because you almost always need to fit and transform your training data at the same time, Scikit-Learn provides `.fit_transform()`. It calculates the measurements and immediately applies them in a single, highly optimized line of code.

---

### **Why are they kept separate? (The Golden Rule)**

This circles back perfectly to the concept of **Data Leakage** discussed earlier. By keeping `fit` and `transform` as two separate commands, you are able to handle your Training Set and Test Set differently:

| Dataset | Method Used | What is happening? |
| --- | --- | --- |
| **Training Set** (`X_train`) | `.fit_transform()` | The algorithm **learns** the parameters (mean, variance, categories) exclusively from the training data, and applies the changes. |
| **Test Set** (`X_test`) | `.transform()` **ONLY** | The algorithm takes the exact parameters it learned from the training data and applies them to the test data. It is **strictly forbidden** from learning new parameters from the test set! |

If you were to use `.fit()` or `.fit_transform()` on your test set, your model would calculate a brand new mean and standard deviation specific to the test data. This ruins the scale, breaks the rules of predicting on "unseen" data, and invalidates your entire machine learning model.